### ISSUE TITLE
Configurable behaviour when no input property match a rule lamda expression within the workflow

### ISSUE THREAD

**Issue by FunksMaName** [microsoft/RulesEngine#1]
Using the sample workflow in the docs, assuming I appended the following rule to the collection: 

`      {
        "RuleName": "GiveDiscount45CurrentYearPurchasers",
        "SuccessEvent": "45",
        "ErrorMessage": "One or more adjust rules failed.",
        "ErrorType": "Error",
        "RuleExpressionType": "LambdaExpression",
        "Expression": "input1.loyalityFactor > 3 AND input1.currentYearPurchaseCount > 1"
      }`

When input1 does not contain the property "currentYearPurchaseCount", we get an exception 

`Operator '>' incompatible with operand types 'Object' and 'Int32' (at index 62)
Unhandled exception. Operator '>' incompatible with operand types 'Object' and 'Int32' (at index 62)`

Do you think there should be a configurable setting to either 

- Skip that rule
- Preferably have "Pass", "Fail", and an additional "UnEvaluated" Result. 

I'm prototyping a credit scoring solution at the moment, and sometimes, for instance, the application does not have a "Business Address Validity" Score. It implies that I have to give it an arbitrary value to make it skip the configured rule when the input is not available.   

Thoughts?

**Comment by abbasc52** [comment]
@FunksMaName agree with you that an exception in this case is undesirable. We should fail that rule whenever exception occurs.

I am unable to see a use case for "UnEvaluated" result. Do you see any area where it might be needed?

**Comment by FunksMaName** [comment]
> I am unable to see a use case for "UnEvaluated" result. Do you see any area where it might be needed?

My thinking behind "UnEvaluated" is that semantically, It has neither passed nor failed that rule, it's just that the rule is inapplicable and cannot be evaluated based on the input data. 

To keep things simple, perhaps "UnEvaluated" behaviour is starting to tread towards specific requirements, and should be handled by the application, not the library.

**Comment by dishantmunjal** [comment]
@FunksMaName What we can do is, that in case of exception we fail the rule and send the exception message to the application thus giving application control if it needs to handle accordingly.
We will put it in next release of the NuGet. 
Will update the issue once released.

**Comment by dishantmunjal** [comment]
Hi @FunksMaName 
We have updated the nuget and the code. It shouldn't throw an exception anymore and should be able to handle the scenario as mentioned above.
Please reopen the issue if it persists.
Please raise another issue if any other issue comes up.

_Happy Coding!!!_ :)
