### ISSUE TITLE
Executing a rule within a rule

### ISSUE THREAD

**Issue by AlahmadiQ8** [microsoft/RulesEngine#10]
First, Thank you for this awesome project. I was looking for a lightweight rules engine and this is exactly what i'm looking for. 

I apologize in advance if my question is not  clear. 

I have a bunch of rules that depend on the value of other rules. Here is an example:

Let's say i have a bunch of rules that evaluate some formulas:

```
Rule1 expression: input.x + input.y
Rule2 expression: input.x / input.y * 5
Rule3 expression: Rule1(input) + input.x
...etc
```

How can i express `Rule3 Expression` in the json file?

**Comment by abbasc52** [comment]
@AlahmadiQ8 RulesEngine primarily targets checking whether an expression is true or false. Are you looking for something beyond that?
Also, Currently we don't particularly have a way evaluate dependent expression, we can think about adding this feature. Could you please provide some more details on the usecase?

**Comment by AlahmadiQ8** [comment]
My apologies for the ambiguity. 

>RulesEngine primarily targets checking whether an expression returns is true or false. Are you looking for something beyond that?

I wanted to use the RulesEngine beyond true or false but to evaluate return values

For example: 

```json
{
	"RuleExpressionType": "LambdaExpression",
	"Expression": "input.Balance / 100 * input.Rounding"
}
```

and then the successValue would be the result the above expression. 

>Currently we don't particularly have a way evaluate dependent expression, we can think about adding this feature

Here is an exmample:

```json
[
  {
    "WorkflowName": "Discount",
    "Rules": [
      {
        "RuleName": "GiveDiscount10",
        "SuccessEvent": "10",
        "ErrorMessage": "One or more adjust rules failed.",
        "ErrorType": "Error",
        "RuleExpressionType": "LambdaExpression",
        "Expression": "input1.country == \"india\" AND input1.loyalityFactor <= 2 AND input1.totalPurchasesToDate >= 5000"
      },
      {
        "RuleName": "GiveDiscount20",
        "SuccessEvent": "20",
        "ErrorMessage": "One or more adjust rules failed.",
        "ErrorType": "Error",
        "RuleExpressionType": "LambdaExpression",
        "Expression": "input1.country == \"india\" AND input1.loyalityFactor >= 3 AND input1.totalPurchasesToDate >= 10000"
      }
      {
        "RuleName": "EligibleForDiscount",
        "ErrorMessage": "Not eligible for any discount",
        "ErrorType": "Error",
        "RuleExpressionType": "LambdaExpression",
        "Expression": "GiveDiscount10 OR GiveDiscount20"
      },
    ]
  }
]
```

**Comment by abbasc52** [comment]
> I wanted to use the RulesEngine beyond true or false but to evaluate return values
> 
> For example:
> 
> ```json
> {
> 	"RuleExpressionType": "LambdaExpression",
> 	"Expression": "input.Balance / 100 * input.Rounding"
> }
> ```
> 
> and then the successValue would be the result the above expression.

Currently we don't support it but it seems a good add-on. We will prioritize it.

As for your second example, we support nested rules if that is what you are looking for:

https://github.com/microsoft/RulesEngine/blob/af53705ab527f3b9502205cbdb9703f65c2980b5/demo/DemoApp/Workflows/Discount.json#L37-L59

Let me know if this helps

**Comment by valxv** [comment]
@abbasc52 I think that @AlahmadiQ8 meant [Forward chaining](https://en.wikipedia.org/wiki/Forward_chaining). Any plans to support this?

**Comment by abbasc52** [comment]
We are planning to introduce Actions to solve this issue #23 . Please comment there if case you need any additional feature
