### ISSUE TITLE
Return a result from rule execution

### ISSUE THREAD

**Issue by Pokerky** [microsoft/RulesEngine#105]
Hello, I'm using the RulesEngine, and i want to know how to return a result from Rule expression

**Comment by abbasc52** [comment]
RulesEngine primarily returns true/false as result. If you are looking for returning an expression on rule success or failure, you can use Output Expression Action - https://github.com/microsoft/RulesEngine/wiki/Actions#outputexpression

**Comment by Pokerky** [comment]
thanks ;)
