### ISSUE TITLE
Problem with null variables with parameter

### ISSUE THREAD

**Issue by williancarvalho** [microsoft/RulesEngine#113]
Hi,

I'm doing some tests where the variables and rules are dynamic, in some scenarios it may happen that some information does not exist and in this case the variable is null.

Ex.:
```
public Task<TReturn> RunProcess(IDictionary<string, object> parameters)
{
      var ruleParameters = parameters.Select(p => new RuleParameter(p.Key, p.Value)); // <-- here one or more values maybe are null
      // create rules engine
      await engine.ExecuteAllRulesAsync("wfName", ruleParameters);
}
```

We are currently unable to deal with this scenario, because the null value causes an error in the construction of the RuleParameter, would there be any alternative way? Perhaps exposing the internal constructor of the _src/RulesEngine/Models/RuleParameter.cs_ class.

**Comment by abbasc52** [comment]
Hi @williancarvalho,
Before providing a fix, i would like to know the details on how are you planning to handle null values in rule? 
I could provide default type of null as object but would that work for the rules you are planning?

**Comment by williancarvalho** [comment]
I'm sorry for answering so late.

In the case that I commented we would have to deal with the null value directly by the rule, like var! = Null. In some rules the null value may correspond to the passage or not through a calculation flow, for example, however they would have to be imputed in the rule in some way.

I even thought of using int.MinValue to be able to use the information in the engine, but I'm not sure if it would be the best way to say that the value does not exist.
