### ISSUE TITLE
Rule config file is not present for the Exámple workflow'

### ISSUE THREAD

**Issue by David-Moreira** [microsoft/RulesEngine#114]
Hello @abbasc52 
RulesEngine does not seem to like "weird chars" on the Workflow Name, like 'Exámple' for example. 
I only tested with 'accents' like : à è ì ò ù not sure about other characters...

Could we fix this?
Example:
![image](https://user-images.githubusercontent.com/22283161/114435559-3331f100-9bbc-11eb-9cd0-147cdd5e7d65.png)

**Comment by asulwer** [comment]
as a temp solution, for example, convert before adding to array HttpUtility.UrlEncode.  adding to the workflow urlencoded and then decoding for string comparison may be a temp solution.

**Comment by abbasc52** [comment]
Hi @David-Moreira,
I am unable to reproduce this (in 3.1.0-preview.3), can you provide more details on the rules file? 

Also please provide which nuget version are you using?

**Comment by David-Moreira** [comment]
Hello @abbasc52 
I was just trying to reproduce this. And I wasn't able with this setup:
![image](https://user-images.githubusercontent.com/22283161/115113900-81f8d580-9f84-11eb-9bd8-83e2c59e157d.png)
Which leads me to believe, it might have to do with loading the data from a file, and the file enconding messing up certain chars. I will have to get back to you on this, on Monday. But I had this happen when loading from BD, so that's strange.

Anyway, I will give you more concrete details on Monday, but I'm guessing the issue might be on my part then, and it is more to do data being passed around and different encodings.

**Comment by David-Moreira** [comment]
Sorry it took so long... busy with other stuff... >.<
So.. I'm on Version 3.0.2
Don't have `bre.GetAllRegisteredWorkflowNames()`
Here's some of my debug information, together with the error:
![image](https://user-images.githubusercontent.com/22283161/115565834-a10fa400-a2b1-11eb-8e07-5c1eae784992.png)
