### ISSUE TITLE
Can't parse Select Linq with index parameter => Func<TSource, int, TResult>

### ISSUE THREAD

**Issue by David-Moreira** [microsoft/RulesEngine#115]
Any idea why this is @abbasc52 ?

Trying to evaluate this expression:
Input.Lista.Where(x=>x.Name!=\"\").Select((x,y)=>(x.Name, y)).Any()

![image](https://user-images.githubusercontent.com/22283161/114718747-38af4880-9d2e-11eb-992e-02c902594905.png)

I did open a ticket over at System.Linq.Dynamic.Core repository, but wondering if I'm missing something? Or is there some workaround? I have a use case where I need to grab both the index and itemSource. Any ideas?

https://github.com/zzzprojects/System.Linq.Dynamic.Core/issues/500

**Comment by abbasc52** [comment]
Hi @David-Moreira , Dynamic linq has slightly different syntax for lambda operator.

instead of `x => x`,  you need to use `it`
in your case 
`Input.Lista.Where(it.Name!="")`

as for `Select((x,y) => (x.Name,y))` i am not sure if select with 2 params is supported by dynamic linq

You can find more details here - https://dynamic-linq.net/expression-language#sequence-operators

**Comment by David-Moreira** [comment]
I didnt know about that specifically, seems like a nice shortcut, but this does work and is closer to how you would actually write in "standard c#":
`Input.Lista.Where(x=>x.Name!="").Any();`

Thank you, I'll do some more digging.

**Comment by abbasc52** [comment]
If you are looking for work-around, you could try creating your util method, something like
`Utils.ToIndexValuePair(Input.Lista.Where(x=>x.Name!=""))`

And the method something along the lines :-

```c#

public IEnumerable<KeyValuePair<int,T>> ToIndexValuePair(IEnumerable<T> mylist){

    return mylist.Select((x,i) => new KeyValuePair<int,T>(i,x));
}

```

Let me know if this works

**Comment by David-Moreira** [comment]
Hello I've already tried wrapping the supposed IEnumerable in a method... But it so happens the type is not actually an Ienumerable it is a IWhereListIterator...

Any other ideas? 😅

**Comment by abbasc52** [comment]
how about adding `ToList()` after your where clause?
Not that efficient but looks like it gets the type right.

Check this - https://dotnetfiddle.net/ooPHa7

**Comment by David-Moreira** [comment]
You're right l'll take a look. Thanks!

**Comment by abbasc52** [comment]
Hi @David-Moreira 

Please look at this sample - https://dotnetfiddle.net/JwExQX
It seems generics are not supported well but you can overcome that with dynamic type.
This should solve your issue.

**Comment by David-Moreira** [comment]
Oh great!! I had tried that before but it did not work. Maybe I didn't use correctly. Oh something else I tried without great success was to parse in a Func or Action since it does not recognzie lambdas... Any ideas for workarounds?

**Comment by abbasc52** [comment]
@David-Moreira Apparently dynamic.linq.core does not play well with generics and extension methods.  Also it currently does not support lambda with parenthesis for parameter
e.g. `c => c == true` works
but `(c) => c == true` fails.

With this limitation it will be difficult to trim down the solution...unless we reimplement linq or wait for the library to fix it.

**Comment by David-Moreira** [comment]
I see, Thanks for taking the time helping with this @abbasc52 much appreciated! :)

**Comment by David-Moreira** [comment]
Hello @abbasc52

So here I am again with this problem... sigh.
So the solution you've helped me find, works nicely on a simple list. But I have a requirement where I need to query Lists within lists... and I want to at least persist the index of the first list items where certain condition was evaluated to true.

But since we are converting to dynamic, it has no idea how to work with collections on subsequent queries... Find example below:
https://dotnetfiddle.net/SPxJWk

I know this isn't an issue with your library, just wondering if you could take a look and see if you have any ideas. I'd appreciate that, Thanks @abbasc52

**Comment by abbasc52** [comment]
Hi @David-Moreira , i am unable to find a simple solution to this problem.
Best approach would be to include index in the model itself, prepopulating it before passing it to RulesEngine.

**Comment by David-Moreira** [comment]
Hello,
Thanks for taking the time. That one also passed through my mind... I figured another solution for my use case, but there's a lot of work behind the scenes... I'm basically keeping track of the list where I want to obtain the index, and I have a Method that executes both the condition to obtain the value, but also the same condition, but to obtain the index and merge them both into the final result.
