### ISSUE TITLE
invalid lambda expression in local parameter throw an exception

### ISSUE THREAD

**Issue by gedoFR** [microsoft/RulesEngine#116]
Hello 
I'm using in the local parameter expression that contains reference with input data.

1.  If the expression in the local parameter cannot be evaluated , the rule engine generates an exception and stop, instead of having the error message in the rule.

On file attachment, for the rulename "checksegmentsLambdaExpressionLocalParameter"
if have the expression : 
segments.Where(x => x.DepartureAirport == \"ZRH\").FirstOrDefault().RemainingDistanceEnd

segments is a list<segment> coming from the RuleParameter list
            var flightPlan = new RuleParameter[]
                {
                    new RuleParameter("segments", Segments)
                };

I'm using the local parameter in that way, for having a more readable expression in the rule and also for using it in the error message.

rule expression :  " lp_remainingDistance > lp_distanceAltnSegment "
"ErrorMessage": " wrong distance [$(lp_distanceAltnSegment)] "

2.  In the RuleName "checksegmentElementAt" the expression to access a specific element in the list is not recognized  : 
"Expression": "segments.ElementAt(0).DepartureAirport"
I have not really understood why this is not possible

Thank you
Your rule engine is really nice. 
 
[FPAPrulesCheckFlightNumberAndSegmentLambdaExpression.txt](https://github.com/microsoft/RulesEngine/files/6323686/FPAPrulesCheckFlightNumberAndSegmentLambdaExpression.txt)

**Comment by abbasc52** [comment]
Hi @gedoFR,



> 1. If the expression in the local parameter cannot be evaluated, the rule engine generates an exception and stop, instead of having the error message in the rule.

This will be handled as a part of #119 



> 2. In the RuleName "checksegmentElementAt" the expression to access a specific element in the list is not recognized :
>    "Expression": "segments.ElementAt(0).DepartureAirport"
>    I have not really understood why this is not possible

RulesEngine internally uses System.Dynamic.Linq.Core which supports limited sequence related(read as linq methods) methods 
For the complete list refer - https://dynamic-linq.net/expression-language#sequence-operators

An alternative would be to convert it to a list(if not already) and using index operator
```c#
segments.ToList()[0].DepartureAirport

or

segments[0].DepartureAirport

```

**Comment by gedoFR** [comment]
hi @abbasc52 ,

Thank you for this quick response.
The fix works fine and I can use an index operator as desired.

Brgds
