### ISSUE TITLE
'GlobalParams' property missing on 'WorkflowRules' from nuget package download

### ISSUE THREAD

**Issue by sappidilovaraju** [microsoft/RulesEngine#122]
I can see the GlobalParams property on WorkflowRules class from git code, but I can't see this property from nuget package library.  Is this should released or not?  If not, when can we except this from nuget package?

**Comment by abbasc52** [comment]
Hi @sappidilovaraju, Global params are available in preview version of nuget. You can find the details in [Changelog](https://github.com/microsoft/RulesEngine/blob/main/CHANGELOG.md) . We are planning to release a non-preview version soon
