### ISSUE TITLE
help  parse  with  contains one of these words 

### ISSUE THREAD

**Issue by caozhq** [microsoft/RulesEngine#133]
Hi， @abbasc52 ， I  am trying to match this expression.   

 new List<string>(){ \"AA\", \"BB\" }.Where(c => input1.Title.Contains(c)   .  There are many selections like  \"AA\", \"BB\", \"CC\", \"DD\" . Any one of these words appears in the input title  will be matched to success. How can I do it ? Thanks !

**Comment by dishantmunjal** [comment]
Hi @caozhq 
You can use Utils class for this. The method can directly be used then in the rules. 
Please refer  - https://github.com/microsoft/RulesEngine/wiki/Getting-Started#resettings

**Comment by caozhq** [comment]
OK. I will try it. Thanks a lot!
