### ISSUE TITLE
Max (x => x.Value)/Max() etc style Expression does not work But FirstOrDefault() Does?

### ISSUE THREAD

**Issue by craigbekker** [microsoft/RulesEngine#155]
I am trying to pass through a List of Values, get the Highest one in the list by doing a Max in a LocalParams.
What confuses me is in the tests in the application you are using FirstOrDefault So I cannot see why Max would not work
I have confirmed that FirstOrDefault(x => x.etc) does not work, as soon as you add a x => you get the following:

Error while compiling rule ``: ')' or ',' expected, in ScopedParam:

This really limits what I can do with the rules engine.  Why is this not supported and how can I get around this?

I have created the following Linqpad Query to try Illustrate what I'm trying to achieve.

`void Main()
{
	List<SomeItem> list = new List<SomeItem>(){
		new SomeItem(){Value = 1},
		new SomeItem(){Value = 2}
	};
	
	list.Max(x => x.Value).Dump();
}

class SomeItem
{
	public int Value;
}
`

This is a trimmed-down version of the rule I'm trying to create

`{
    "WorkflowName": "test",
    "Rules": [
        {
            "RuleName": "Level 1",
            "SuccessEvent": "1",
            "ErrorMessage": "One or more adjust rules failed.",
            "ErrorType": "Error",
            "localParams": [
                {
                    "Name": "maxItem",
                    "Expression": " Payload.ListOfData.Select(x => x.Value).Max()"
                }
            ],
            "RuleExpressionType": "LambdaExpression",
            "Expression": "maxItem <= 2"
        }
    ]
}`

**Comment by David-Moreira** [comment]
Hello,
I'm not the maintainer of this library, but taking a quick look at your issue, your expression should use max the same way you tested it, taking in a selector.

Also I have also made this mistake myself, but the maintainer pointed me in the right direction, the correct documentation for what's able to be parsed is in the dynamic linq library docs : https://dynamic-linq.net/expression-language#sequence-operators
Which looks pretty close to the linq we are used to, but does not support every single one of them.

**Comment by craigbekker** [comment]
Thank you David. It might be a good idea for them to add this to the documentation as it's a little unclear.
I was actually pondering last night if its not a different flavour of linq

**Comment by abbasc52** [comment]
Thanks @David-Moreira for providing the answer.
@craigbekker you are right, I will include this to the documentation to ensure people are aware of this.

**Comment by asulwer** [comment]
so this question is answered how?  and what is the correct syntax to make something like this work?

**Comment by David-Moreira** [comment]
Hello, 
It's in the thread. You should take a look at the dynamic linq docs and use the same syntax / contracts.

For the max the syntax should be something like :
list.Max(x => x.Value)

**Comment by abbasc52** [comment]
Closing this issue . Also the documentation related to operations have been added to docs - https://microsoft.github.io/RulesEngine/#c-expression-support

**Comment by dev-thinks** [comment]
Hello @abbasc52 ,

I see the dynamic linq is supporting .Select(predicate) on IEnumerable. but still am getting `')' or ',' expected` exception. not sure what am missing here. any help or your insights is helpful. Thank you.

here is my expression on my input collection, 

`{
        "successEvent": "10",
        "errorMessage": "test rule failed",
        "errorType": "Error",
        "ruleExpressionType": "LambdaExpression",
        "expression": " ExpressionUtils.CheckEquals(input1.data.Select(sd=>sd.License), \"1\") ",
        "ruleName": "test rule"
      }`

**Comment by abbasc52** [comment]
@dev-thinks is it possible to share a sample input  and data type of it?

**Comment by dev-thinks** [comment]
sure. attached example input in json format; inputdata.txt

It is anonymous data type, am trying to convert this json string into dynamic like this (btw, this is working for other rules without .Select(...) ),
`var converter = new ExpandoObjectConverter();
return JsonConvert.DeserializeObject<ExpandoObject>(inputdatajson, converter);`
[inputdata.txt](https://github.com/microsoft/RulesEngine/files/7275476/inputdata.txt)

**Comment by dev-thinks** [comment]
@abbasc52 I would like to access array/list present in license object in the example json.

**Comment by dev-thinks** [comment]
I figured it out; I missed the dynamic linq query syntax "it" @abbasc52
