### ISSUE TITLE
Attempting simple demo use of library but getting JsonSerializationException

### ISSUE THREAD

**Issue by kknd4eva** [microsoft/RulesEngine#170]
I'm assuming I've made a stupid mistake here, but wondering if someone could assist? 

My rules.json is as follows: 

```
[
  {
      "WorkflowName": "DeliverToMatchingSuburb",
      "Rules": [
        {
          "RuleName": "MatchingSuburb",
          "Expression": "customer.PostCode == pharmacy.PostCode"
        }
      ]
  }
]
```
My code:
```
            string[] readText = File.ReadAllLines("rules.json");
            Customer c = new Customer();
            Pharmacy p = new Pharmacy();
            var pharmacies = p.GetPharmacies();
            var customers = c.GenerateCustomers();


            var re = new RulesEngine.RulesEngine(readText, null);
```

My attempt to pass 'readText' into the RulesEngine however gives me the following exception? 

`Newtonsoft.Json.JsonSerializationException: 'Unexpected end when reading JSON. Path '', line 1, position 1.'`

**Comment by alberto-guerrero** [comment]
@kknd4eva , reviewing: https://github.com/microsoft/RulesEngine/blob/main/demo/DemoApp/BasicDemo.cs

It looks like they deserialize the json configuration into a List of WorkflowRules first:

```
var fileData = File.ReadAllText(files[0]);
var workflowRules = JsonConvert.DeserializeObject<List<WorkflowRules>>(fileData);

var bre = new RulesEngine.RulesEngine(workflowRules.ToArray(), null);
```

Hope this helps.

**Comment by kknd4eva** [comment]
> @kknd4eva , reviewing: https://github.com/microsoft/RulesEngine/blob/main/demo/DemoApp/BasicDemo.cs
> 
> It looks like they deserialize the json configuration into a List of WorkflowRules first:
> 
> ```
> var fileData = File.ReadAllText(files[0]);
> var workflowRules = JsonConvert.DeserializeObject<List<WorkflowRules>>(fileData);
> 
> var bre = new RulesEngine.RulesEngine(workflowRules.ToArray(), null);
> ```
> 
> Hope this helps.

Thanks, yes it does - I completely missed the overloads for that constructor, one of which accepts 'workflowrules[]'. Thank you! This can be closed.
