### ISSUE TITLE
Suggestion to improve WiKi about ReSetting and custom methods

### ISSUE THREAD

**Issue by afborgesDev** [microsoft/RulesEngine#18]
Hi everyone. I think that could be helpful for others that are starting with the lib to know how to register and use custom class. So then I've copied and edited the Wiki part about Settings to show how to do it. 

Thanks.

---
**ReSettings**

This model is a list of custom types. While, lambda expressions are quite powerful, there is a limit to what they can do because of the fact that the methods that a lambda expression can do are limited to [System namespace](https://docs.microsoft.com/en-us/dotnet/api/system) of [.Net framework](https://docs.microsoft.com/en-us/dotnet/framework/).

To use more complex and custom classes and have some logics which are way too complex to be written into a lambda expression, these settings come into picture. If the user wants to create a custom method to run for the rule to be used, these settings help them.

Example –

You can create a public class called Utils and include a method in it which check contains in a list.
```csharp
using System;
using System.Linq;

namespace RE.HelperFunctions
{
    public static class Utils
    {
        public static bool CheckContains(string check, string valList)
        {
            if (String.IsNullOrEmpty(check) || String.IsNullOrEmpty(valList))
                return false;

            var list = valList.Split(',').ToList();
            return list.Contains(check);
        }
    }
}
```
And this can be then used in lambda expression in a very simple manner like this –
```
"Expression": "Utils.CheckContains(input1.country, \"india,usa,canada,France\") == tru
```

> 
> To use the custom class when evaluating the rules:
> 
> 1) Register the class:
> 2) Then pass settings through rules engine.
> ```csharp
> var reSettingsWithCustomTypes = new ReSettings { CustomTypes = new Type[] { typeof(Utils) } };
> new RulesEngine.RulesEngine(workflowRules.ToArray(), null, reSettingsWithCustomTypes);
> ```

**Comment by abbasc52** [comment]
Thanks @afborgesDev for your input. We have included the information in the documentation
