### ISSUE TITLE
[Doc] Image broken

### ISSUE THREAD

**Issue by fernandolamp** [microsoft/RulesEngine#198]
Hi, the image  of the link https://github.com/microsoft/RulesEngine/wiki/Introduction#what-is-the-rules-engine is broken

![image](https://user-images.githubusercontent.com/18193204/128912349-87d8869d-8d47-47e3-86ac-faa7359c7e8e.png)

https://github.com/microsoft/RulesEngine/raw/master/assets/BlockDiagram.png

Should this image be the same of the README? (https://github.com/microsoft/RulesEngine/blob/main/assets/BlockDiagram.png) ?

Tks !

**Comment by abbasc52** [comment]
Thanks for pointing out. I have fixed the link now 😄
