### ISSUE TITLE
Enum references in Expressions

### ISSUE THREAD

**Issue by alexreich** [microsoft/RulesEngine#209]
Often rule expressions need to reference enumerated types. There are 2 issues when doing so described below. Any ideas on best practice are appreciated.

1. If it's a simple rule and 1 global param (perhaps local param works as well), a reference can be made in the string expression to the fully qualified type name running the engine all the way down to the enum itself without explicitly passing the enum successfully. However, introduction of the 2nd or more params return expression errors. In the later example of the 2nd or more enum references, the 1st param including the enum still works. 
2. As a work around to the above, a helper function was written to pass enums as `IEnumerable<ScopedParam>` - the following is sample usage:

```csharp 
workflow.GlobalParams = HelperFunctions.Types.ToScopedParams<Fruits>();
```

Below is a more complete example along w/the helper method which allows for an optional prefix to be passed:

```csharp 
        public enum SecurityRoles
        {
            None,
            Viewer,
            Reviewer,
            Supervisor,
            Administrator
        }
```

```csharp 
workflow.GlobalParams = HelperFunctions.Types.ToScopedParams<SecurityRoles>("Role_");
```

```csharp 
       public static IEnumerable<ScopedParam> ToScopedParams<T>(string Prefix = "")
        {
            List<ScopedParam> scopedParams = new List<ScopedParam>();
            foreach (int x in Enum.GetValues (typeof(T)))
            {
                ScopedParam scopedParam = new ScopedParam();
                string Name = Enum.GetName(typeof(T), x);
                if (Prefix != "")
                {
                    scopedParam.Name = Prefix + Name;
                }
                else
                {
                    scopedParam.Name = Name;
                }
                scopedParam.Expression = x.ToString();
                scopedParams.Add(scopedParam);
            }
            return scopedParams;
        }
```

**Comment by abbasc52** [comment]
Hi @alexreich,
You can use enums directly in rules, but you will need to add the type in CustomTypes for RulesEngine to reference it.
In your case you would need to add the following in ReSettings:
```
var settings = new ReSettings{
			CustomTypes = new Type[]{typeof(SecurityRoles)}
		};
```
You can refer this sample code - https://dotnetfiddle.net/YEtmfI

**Comment by alexreich** [comment]
Thanks @abbasc52 !

**Comment by tanveerbadar** [comment]
This solved the problem for me too. Thank you so much!
