### ISSUE TITLE
RuleEngine constructor with duplicate WorkflowsRules throws exception

### ISSUE THREAD

**Issue by marknisc-soft** [microsoft/RulesEngine#210]
When using the ctor overload RulesEngine(WorkflowRules[] workflowRules... when a duplicate rule is found an exception will be thrown: "Cannot add workflow `{workflow.WorkflowName}` as it already exists. Use `AddOrUpdateWorkflow` to update existing workflow"

The expectation would be when using this overload it will call AddOrUpdateWorkflow instead of AddWorkflow so exception is not thrown

**Comment by abbasc52** [comment]
@marknisc-soft , it is a design decision to make it explicit to users that they are overriding existing workflow.

If you want to still want to add Multiple workflows which may have duplicate, you can initialise RulesEngine with emty list of workflow and call AddOrUpdateWorkflow to add all workflows
