### ISSUE TITLE
Can I use Regex in the rules?

### ISSUE THREAD

**Issue by Arikli** [microsoft/RulesEngine#217]
Is it possible to use Regex.IsMatch as a rule?
 something like this for example:
"Expression": "new Regex(@\"a\").IsMatch(input1.someString)"

when I'm debugging I get an exception " Type 'Regex' not found".

Thanks.

**Comment by alexreich** [comment]
Hi @Arikli,

Not in an expression as Rules Engine is built on [LINQ](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/ef/language-reference/supported-and-unsupported-linq-methods-linq-to-entities). To get around this, rewrite the expression using SQL via LINQ, pass the results of your RegEx in as a ScopeParam or evaluate the RegEx outside of the engine itself when evaluating the outcome (e.g. Rule.IsSuccess && Regex.IsMatch).

Hth.

**Comment by abbasc52** [comment]
@Arikli , You need inject Regex type for RulesEngine to recognize it.

You can do it by passing custom type in ReSettings:
```c#
var reSettings = new ReSettings{
  CustomTypes = new Type[]{  typeof(Regex) }
};

var engine = new RulesEngine.RulesEngine(workflows,logger, reSettings);
```

**Comment by ekennedy6334** [comment]
RegexOptions.IgnoreCase not included?

**Comment by alexreich** [comment]
> RegexOptions.IgnoreCase not included?

In order to include Enums in the namespace, it would need to be passed in, just like Regex itself:

```
var reSettings = new ReSettings{
  CustomTypes = new Type[]{  typeof(Regex), typeof(RegexOptions) }
};

var engine = new RulesEngine.RulesEngine(workflows,logger, reSettings);
```
