### ISSUE TITLE
result as input 

### ISSUE THREAD

**Issue by grahamehorner** [microsoft/RulesEngine#22]
allow more complex rules to be defined by taking the result of an evaluated message and feeding it back into the rules engine with the same/different determined by the value and/or triggering some defined async action i.e. HTTP POST

**Comment by abbasc52** [comment]
Hi i think you are looking for chaining rules and action triggers. We are evaluating on how we can add these features.

**Comment by abbasc52** [comment]
This will be implemented as a part of #23
