### ISSUE TITLE
Call async method in Expression

### ISSUE THREAD

**Issue by KonstantinosP7** [microsoft/RulesEngine#226]
Hello,

I have followed the example in this issue: https://github.com/microsoft/RulesEngine/issues/71 and I managed to call a non-static method. 
Is there a way to call an __async__ method in the Expression property of the Rule and get its value __without__ using `.Result` ?

Main code: 
```c#
var utils = new Utils(config);
var engine = new RulesEngine.RulesEngine(workflowrules.ToArray(), null, reSettings: reSettings);
var resTree = await engine.ExecuteAllRulesAsync("workflow", new RuleParameter("utils", utils));
```

Async Method: 
```c#
public class Utils
{
       public async Task<int> ResultMethod()
       {
             return await Task.FromResult(1);//dummy code 
       }
}

```

JSON Workflow:
```json
{        
            "RuleName": "Rulename",
            "ErrorMessage": "Error Message",
            "ErrorType": "Error",
            "RuleExpressionType": "LambdaExpression",
            "Expression": "utils.ResultMethod().Result >= 3"
}
```

Thank you in advance,

**Comment by abbasc52** [comment]
Hi @KonstantinosP7, unfortunately there is no other way to call async method other that with `.Result`. As Expression do not support `async await` syntax

**Comment by KonstantinosP7** [comment]
Thanks @abbasc52 for your answer. However, is there any way that this problem (async method call without `.Result`) can be solved with Rule Engine? Like adding another parameter (that is not an Expression) and use it as an input in Expression? ( localParams e.g. )

**Comment by KonstantinosP7** [comment]
Thanks @abbasc52 for your answer. However, is there any way that this problem (async method call without '.Result) can be solved with Rule Engine? Like adding another parameter (that is not an Expression) and use it as an input in Expression? ( localParams e.g. )

**Comment by abbasc52** [comment]
HI @KonstantinosP7 , can you explain your usage for async methods? I would like to know your thought process and suggestions.

**Comment by KonstantinosP7** [comment]
I would like to pass as a parameter the async method but it should be executed only when the subrule is executed (to save IO operations, if the others subrules do not evaluate to true there is no reason to do extra io without reason). 

Let's say that the async method performs db operations and I retrieve an object to evaluate in the Rule. Is there another way to get the async method result without the `.Result` ? 

For example, can we have a Rule dictionary with key value where key is an identifier and value is a Func<>
, that includes the async method, and it is called only when the Expression of the Rule refers to it?

**Comment by abbasc52** [comment]
@KonstantinosP7 the async method would only be called when the rule containing is executing.
I think the problem you are facing is all rules are getting evaluated regardless of the previous subrules.

Have you tried setting `NestedRuleExecutionMode` to `Performance` in ReSettings?
It allows you to skip rule execution that won't change the result of parent rule. If the rule is skipped, even your async method call should be skipped.

https://github.com/microsoft/RulesEngine/blob/2af72285bc0ec0cd2b6cc7f2886c94e4fb41807d/src/RulesEngine/Models/ReSettings.cs#L47-L50

https://github.com/microsoft/RulesEngine/blob/2af72285bc0ec0cd2b6cc7f2886c94e4fb41807d/src/RulesEngine/Models/ReSettings.cs#L62-L72

**Comment by KonstantinosP7** [comment]
Thank you @abbasc52 again for your answer. 

My issue is not the rule skip, I have already the performance releated setting enabled. 
The problem is not that with .Result it is always executed, but that I must use the .Result.
 
My use case is that alongside simple rules in the Expression (e.g. `request.NumberVar == 2 `)
I also have IO operations that are performed inside async methods. 

Yes, it is executed after subrule `request.NumberVar == 2` evalutes to true ,
but i have to use `.Result` which is generally a bad practise. 

As a suggestion could we add in the workflow/rule object an extra property 
that will not be an expression but a function?

The function will asynchronously be executed only when it is needed.
The result should be saved to a param (like an local param) and used inside the subrules.

**Comment by abbasc52** [comment]
Hi @KonstantinosP7, unfortunately we don't have any plans to improve this functionality. I will be closing this issue as it is not a blocker.
