### ISSUE TITLE
Workflow class not available but can see WorkflowRules

### ISSUE THREAD

**Issue by greektreat** [microsoft/RulesEngine#227]
I Installed 3.3.0 on a .Net Standard 2.1 project.
I am trying to create my first Workflow
I tried
` var wf = new Workflow { WorkflowName = eventName };`
but it states  the Type or Namespace is not found.
right under it I can do this and it resolves properly
`var wfr = new WorkflowRules { WorkflowName = eventName };`

I've uninstalled the NuGet and Reinstalled it. Also I tried to version 3.2.0 with same problem
. been trying to figure this out for about 1 hr.

**Comment by greektreat** [comment]
Figured it out Alex Reich's change was from August 13. The latest version 3.3.0 does not have this change

**Comment by Groovejets2** [comment]
When I use the latest Nuget package v3.3.0 this does not work. Same issue going back in packages: 

var workflow = JsonConvert.DeserializeObject<List<Workflow>>(ruleData);

It wants me to change Workflow to WorkflowRules which breaks my code.

WorkflowRule is marked as Obsolete in the code.

When I take the code version 3.3.0 and build it and reference the DLL this works above as pasted here. 

Does anyone know why this happens?

**Comment by abbasc52** [comment]
HI @Groovejets2 , The latest changes have yet to be deployed as nuget. We will deploy it with other consolidated changes soon
