### ISSUE TITLE
WorkFlow Not avaliable in Nuget v3.3.0 but works in Code Build of v3.3.0

### ISSUE THREAD

**Issue by Groovejets2** [microsoft/RulesEngine#229]
When I use the latest Nuget package v3.3.0 this does not work. Same issue going back in packages:

var workflow = JsonConvert.DeserializeObject< List < Workflow > > (ruleData);

(Spaces added above so the comment shows correctly)

Workflow above is unrecognized. Visual Studio suggests I change Workflow to WorkflowRules which breaks my code.

WorkflowRule is marked as Obsolete in the code.

When I take the code version 3.3.0 and build it and reference the DLL this works above as pasted here.

When I install the Nuget Package v3.3.0 and manually replace the DLL with the code build DLL from the Git Repo v3.3.0 it works. 

My summation is something is missing in the deployed NugetPackage v3.3.0 that is in the Git Repo v3.3.0

Does anyone know why this happens?

**Comment by abbasc52** [comment]
@Groovejets2 the main branch contains code which may not be released yet.
If you want to compare code for nuget, you can compare it with the tagged version. In this case - https://github.com/microsoft/RulesEngine/tree/v3.3.0

**Comment by Groovejets2** [comment]
Thank you abbasc52. I will try that
