### ISSUE TITLE
Introduce Actions on Rule evaluation

### ISSUE THREAD

**Issue by abbasc52** [microsoft/RulesEngine#23]
Currently RulesEngine only returns true or false.  We are planning to introduce **Actions** which will provide a way to extend the existing functionality.

Along with the functionality we will provide the following **Actions** out-of-box:
- An action to return a result based on an expression evaluation
- ~~An action to invoke other rule(Rule chaining) with ability to use output of current rule~~ (Deferred)

Addition feature requirement:
- Allow registering custom actions

**Comment by balasherkar** [comment]
Please, may i know when this will be available ?

**Comment by abbasc52** [comment]
Hi @bala3011s this feature is still under design phase, i will update on this thread when we have a tentative release date for this

**Comment by andreujuanc** [comment]
Hi, for now what I've done is that I store an expression on the SuccessEvent and execute it with the same rule parameters. Code I'm using is basically the same as the engine (almost copy pasta)
So my rule looks like this: (this is a terrible example BTW)

```C#
// I only  use one input , which is typed and composed before any rule is executed
var input = new {
    country = "india",
    total = 40,
    shippingCost = 10
  // ... lot more info here
}
...
  {
        "RuleName": "PerCountryDiscount",
        "SuccessEvent": "input.total * 0.20",
        "ErrorMessage": "One or more adjust rules failed.",
        "ErrorType": "Error",
        "RuleExpressionType": "LambdaExpression",
        "Expression": "input1.country == \"india\" || input1.country == \"spain\" "
      },
     {
        "RuleName": "SpanishShippingCosts",
        "SuccessEvent": "input.total > 80 ? 0 :  input.shippingCost  ",
        "ErrorMessage": "One or more adjust rules failed.",
        "ErrorType": "Error",
        "RuleExpressionType": "LambdaExpression",
        "Expression": "input1.country == \"spain\""
      },
```

**Comment by asulwer** [comment]
> Hi, for now what I've done is that I store an expression on the SuccessEvent and execute it with the same rule parameters. Code I'm using is basically the same as the engine (almost copy pasta)
> So my rule looks like this: (this is a terrible example BTW)
> 
> ```cs
> // I only  use one input , which is typed and composed before any rule is executed
> var input = new {
>     country = "india",
>     total = 40,
>     shippingCost = 10
>   // ... lot more info here
> }
> ...
>   {
>         "RuleName": "PerCountryDiscount",
>         "SuccessEvent": "input.total * 0.20",
>         "ErrorMessage": "One or more adjust rules failed.",
>         "ErrorType": "Error",
>         "RuleExpressionType": "LambdaExpression",
>         "Expression": "input1.country == \"india\" || input1.country == \"spain\" "
>       },
>      {
>         "RuleName": "SpanishShippingCosts",
>         "SuccessEvent": "input.total > 80 ? 0 :  input.shippingCost  ",
>         "ErrorMessage": "One or more adjust rules failed.",
>         "ErrorType": "Error",
>         "RuleExpressionType": "LambdaExpression",
>         "Expression": "input1.country == \"spain\""
>       },
> ```

could you explain this more?  SuccessEvent is always a string, that equation is never evaluated

**Comment by andreujuanc** [comment]
Sorry, maybe I explained my self poorly. 
So I **manually** execute the expressions in the successEvent as string that comes from the successfully ran rules.
I just use DynamicExpressionParser.ParseLambda, that's it.

**Comment by geffzhang** [comment]
Is the design finished？

**Comment by abbasc52** [comment]
@geffzhang I have started implementation on this part. I plan to release a preview version of it in 2 weeks.

**Comment by David-Moreira** [comment]
@abbasc52 Could you further explain this point?
"An action to return a result based on an expression evaluation"

Currently I have seen a few people wondering if this is possible and I'd like that to be supported to: 
Being able to run custom logic on success. Like a lambda. Is this what you are working on now? I am currently interested in using your RulesEngine component for a project I am working on, and this is a feature I need.
I was thinking on modifying it to accomodate something simple based on your scheme like introducing:
"SuccessExpressionType" : "LambdaExpression" and then, if this is defined, have the SuccessEvent support lambda expression by just simply generating and compiling them from SuccessEvent similarly to what @andreujuanc  described.
But if you're already working on it, then that would be awesome and I wouldn't need to be customizing your component.

**Comment by abbasc52** [comment]
@David-Moreira  i am trying to come up with a generic way for people to extend the RulesEngine as per their needs. That is what i mean when i say `Actions` 
Regarding `An action to return a result based on an expression evaluation` i will be providing some out-of-the-box actions which can take care of some common scenarios. One of them is as you guessed evaluating a LambdaExpression on rule success using the exact same config and parameter that you passed to RulesEngine and essentially will result in similar output as what @andreujuanc  described. 

You can refer [my branch](https://github.com/microsoft/RulesEngine/blob/users/abbasc52/add-actions) for a sneak peek on what is to come.

**Comment by David-Moreira** [comment]
@abbasc52 I see, awesome then. I'll take a look at the branch.
I think this is a good project, I might be helping you with some stuff from time to time if you'd like.
Thanks!

**Comment by andreujuanc** [comment]
Project is cool indeed! It just need to be more "dynamic" and pluggable.

**Comment by jopmiddelkamp** [comment]
Impressive project @abbasc52! 

I've noticed you've opened a PR and taken a look at your branch. Now I can't seem to figure out how you've intended to configure a custom action.. This is what I've come up with but it's not working. Can you maybe give me some advice on how to implement the custom actions? This might be interesting for one of our projects.

```csharp
            var bre = new RulesEngine.RulesEngine(workflowRules.ToArray(), null, new ReSettings
            {
                CustomActions = new Dictionary<string, Func<ActionBase>>
                {
                    {LowerCreditHistoryAction.Key, () => new LowerCreditHistoryAction(new NullLogger<LowerCreditHistoryAction>())}
                }
            });
```

```csharp
    public class LowerCreditHistoryAction : ActionBase
    {
        internal const string Key = "lowerCreditHistoryAction";
        
        private readonly ILogger _logger;

        public LowerCreditHistoryAction(ILogger logger)
        {
            _logger = logger;
        }
        
        public override async ValueTask<object> Run(ActionContext context, RuleParameter[] ruleParameters)
        {
            var personalData = ruleParameters.FirstOrDefault(r => r.Name == "personalData")?.Value as dynamic;
            if (personalData == null)
            {
                _logger.LogError($"The personal data is not available in {nameof(LowerCreditHistoryAction)}.");
                return null;
            }

            var oldValue = personalData.Value.creditHistory as string;
            var newValue = "bad";
            personalData.creditHistory = newValue;
            _logger.LogInformation($"Changed the creditHistory from {oldValue} to {newValue}.");
            
            return newValue;
        }
    }
```

```json
      {
        "RuleName": "GiveDiscount25",
        "ErrorMessage": "One or more adjust rules failed.",
        "ErrorType": "Error",
        "RuleExpressionType": "LambdaExpression",
        "Expression": "input1.country != \"india\" AND input1.loyalityFactor >= 2 AND input1.totalPurchasesToDate >= 10000 AND input2.totalOrders > 2 AND input3.noOfVisitsPerMonth > 5",
        "Actions": {
          "onSuccess": {
            "Name": "LowerCreditHistoryAction"
          }
        }
      },
```

**Comment by abbasc52** [comment]
@jopmiddelkamp i am still working on the documentation for custom actions but your registration seems correct. Can you share what error you are getting?

**Comment by jopmiddelkamp** [comment]
@abbasc52 I'm not getting any error at all it just prints 
```
Running CustomActionDemo....
Discount offered is GiveDiscount25 % over MRP.
```
Which is makes sense for me as I've removed the SuccessEvent in the rule JSON. But it's not hitting the action at all..

Here is a link of the feature branch I'm using

https://github.com/jopmiddelkamp/RulesEngine/tree/jopmiddelkamp/actions-question

**Comment by abbasc52** [comment]
@jopmiddelkamp to not break existing functionality, i ended up creating a separate method for Action related workflows, it behaves little differently from the existing `ExecuteRule` method. 
You can find more details and sample usage here - https://github.com/microsoft/RulesEngine/wiki/Actions
I will update it to add custom registration part as well

**Comment by jopmiddelkamp** [comment]
@abbasc52 I see, I've got it working now. Cheers!

**Comment by David-Moreira** [comment]
Hello,
@abbasc52 could you explain why what made you do this distinction, please? Why wouldn't you also give the option to run all rules and corresponding actions of a workflow? Being able to chain other rules with an action if a nice addition tough.

**ExecuteRule** | **ExecuteActionWorkflowAsync**
Takes workflowName as input and executes all rules under it | Takes workflowName and ruleName as an input and executes only that rule and any corresponding action associated with it

**Comment by abbasc52** [comment]
Hi @David-Moreira ,
When i started with design earlier, i did it for simplification as the ability to run all rules and corresponding actions could create confusion (specially when you couple it with rule chaining). Also custom action creation can give a lot of freedom to people, I would like to add `run all` functionality only if it is really required as it makes debugging difficult.

For users who really require running all rules and corresponding actions, we can do that by a simple loop, although it creates a slight overhead of retrieving rule names for the workflow.

I can solve this concern in two ways:
1. Provide a way to retrieve all rules by passing a workflowname
2. Creating a method in the library which can loop through `ExecuteActionWorkflowAsync` for all rules under the workflow

I would prefer going with `approach 1` if required as actions can be async operation and i would prefer users managing parallelism for it.

**Comment by David-Moreira** [comment]
I see, makes sense. Wanted to know your though process. And I will share mine. 
I do think its a functionality people would like, whether debugging is difficult or not. And that can be mitigated by having the option to enable a more detailed log.. i.e: 

1. running rule: "xpto"
2. executed successully or the following error ocorred
3. executing action for rule "xpto"
4. executed successully or the following error ocorred

The rule chaining does still help having the power to run multiple rules in a workflow but I think it may limit it a little. For example, how could you do the following with rule chaining?
Rule 1: 
OnFailure: "1x1"
OnSuccess: Run rule2

But what if for Rule1 being false, I want to not only run that output action, but also still run another rule, to do some more validation and take appropriate action. Do you start adding more complexity to the Actions, or you just run everything and let the user decide how he uses the library, even if he ends up making it harder upon himself to debug at the cost of functionality and "power".

What I expect to happen is people having to create additional code executing all rules, and for the OnSucess/OnFailure upon which they want to take action, having to take the additional step of calling the ExecuteActionWorkflowAsync upon the rules they need, or just looping through every rule in the workflow and calling ExecuteActionWorkflowAsync as you've said. Both options requiring additional code by the consumers of your library.

Personally as a consumer of this library, I would like to see, your tought process being kept but add one of the options you mentioned. As I am one of those people using your library and had to setup a contigent solution to have the "Actions functionality" in the current release, and I took the approach to run the actions on all rules that have it explicity defined.

This is my opinion, however, you've already designed and went through a though process, the feedback of other people who use the library is important too.

**Comment by abbasc52** [comment]
Hi David, that was really insightful!
From all the feedback i received, there are 2 main scenarios that surfaced:
1. Use RulesEngine for validation purpose with possibility return custom output or do some custom operation
2. Enable workflow like execution where you chain different rules and pass on results from one rule to another.

The first scenario is the extension of current usage of RulesEngine and after thinking about it, i do agree that having similar interface of `ExecuteRule` makes sense.

The second scenario is new use-case and it is similar to having a logic app with the power of expression.

That's what led to the current design. 
But your point is valid, i think clubbing these 2 scenarios together creates an overhead for both implementations. 

So let me think over it, if i am planning to support both scenarios, i would rather make `ExecuteRule` support actions and return the same format and similar experience for `scenario 1`.

For the `scenario 2`, `ExecuteActionWorkflowAsync` is more appropriate

**Comment by David-Moreira** [comment]
@abbasc52 what you just described, seems good to me. 
However for scenario 1, the chaining stops making sense I guess, in which case maybe it should not be available for scenario 1, maybe only the output actions.

**Comment by abbasc52** [comment]
preview version with actions has been released as github package here - [RulesEngine 3.0.0-preview.1](https://github.com/microsoft/RulesEngine/packages/449001)

Details on usage can be found here - https://github.com/microsoft/RulesEngine/wiki/Actions

**Comment by michaelstaszewski** [comment]
Custom actions are really nice. As I start writing more complex rules, I'm not seeing what I would expect. Here is a sample workflow with nested rules.

```
[
    {
        "WorkflowName": "WorkflowTest",
        "Rules": [
            {
                "RuleName": "Level0Rule0",
                "SuccessEvent": null,
                "ErrorMessage": null,
                "ErrorType": "Error",
                "Operator": "Or",
                "Rules": [
                    {
                        "RuleName": "Level1Rule0",
                        "SuccessEvent": null,
                        "ErrorMessage": null,
                        "ErrorType": "Error",
                        "RuleExpressionType": "LambdaExpression",
                        "Expression": "false"
                    },
                    {
                        "RuleName": "Level1Rule1",
                        "SuccessEvent": null,
                        "ErrorMessage": null,
                        "ErrorType": "Error",
                        "RuleExpressionType": "LambdaExpression",
                        "Expression": "true",
                        "Actions": {
                            "OnSuccess": {
                                "Name": "MyCustomAction",
                                "Context": {
                                    "MyContext": "MyValue"
                                }
                            }
                        }
                    }
                ]
            }
        ]
    }
]
```

The final leaf rule specifies a custom action. My brain wants this to be the value of Results[0].ActionResult.Output that is available post-execution, but Results[0].ActionResult.Output is null. Even when I drill into ChildResults, ActionResult for that leaf rule is null.

Having all action results available post-execution would be ideal. I've tried using `ExecuteActionWorkflowAsync` passing in `WorkflowTest` and `Level1Rule1` in and get `System.ArgumentException: 'Workflow "WorkflowTest" does not contain any rule named "Level1Rule1"'`.

Is it possible to retrieve action results from nested rules? I think I can flatten my rule hierarchy to resolve this and leave custom actions at top-level rules. The flatter hierarchy is easier to write the json, but in my use case I'm ending up with rules from various paths in the rules logic all jumbled up at the same level so it's more difficult to digest the flow.

**Comment by abbasc52** [comment]
@michaelstaszewski i have created a separate issue to track this- #89 . Once we enable this you should be able to use nested rules with actions.

**Comment by abbasc52** [comment]
Closing this issue as Actions are live with v3 . I have updated the initial description to match current implementation.
