### ISSUE TITLE
Pattern for handling order-dependent rules with an EF/database rule store

### ISSUE THREAD

**Issue by isaacdontjelindellblp** [microsoft/RulesEngine#242]
I'm trying to use Rule Engine inside of an existing project that uses Entity Framework Core as the object store. I've gotten everything wired together to store and manage WorkflowRules, Rules, and ScopedParams in the database.

However, I'm trying to figure out the best way to handle the ordering of rules within a workflow. For example, I have a workflow with 6 rules, which have a specificity precedence.  

If an input matches the "first" rule, that's the one that should be used.

If an input doesn't match the first 5 rules, the 6th rule is a catch-all that will result in a sensible default SuccessEvent.

Is there any good way of ordering rules such that this is preserved? When I initially add the workflow and rules into the database (via EF Core) I know what the order is, but the Rule type doesn't have any property that can be used to specify the order when loading the rules back from the database.

**Comment by isaacdontjelindellblp** [comment]
I've figured out that I can use the Properties dictionary on the Rule type to store an order. It's a bit hacky (because I have to re-order the rules after loading from the database, since Entity Framework can't understand the serialized JSON dictionary), but it does work.

However, I have essentially the same question about params. I'm defining a set of GlobalParams for the workflow, and it would be nice to be able to re-use params in other params. This seems to work fine when reading from JSON, since the params are defined in order, but when loading from the database, there's no way to preserve that order.

Is this something that's possible?

**Comment by abbasc52** [comment]
Hi @isaacdontjelindellblp, there is no direct way to do this in RulesEngine as of now. 

We can investigate having an optional sort order property in scoped params to help with ordering.

**Comment by alexreich** [comment]
@isaacdontjelindellblp, an example of full EF sorting at all levels is in the [RulesEngineEditor](https://github.com/alexreich/RulesEngineEditor) project.

Take a look at the [RulesEngineEditorServer](https://github.com/alexreich/RulesEngineEditor/tree/main/demo/RulesEngineEditorServer) demo example:

```csharp
WorkflowDatas = db.Workflows.Include(i => i.GlobalParams.OrderBy(o => o.Seq)).Include(i => i.Rules.OrderBy(o => o.Seq)).ThenInclude(i => i.Rules.OrderBy(o => o.Seq)).ThenInclude(i => i.LocalParams.OrderBy(o => o.Seq)).ToList();
```

From here, it could be converted to `WorkflowRules[]` (soon to be `Workflow[]`) via JSON Serialize/Deserialize and passed to RulesEngine (this is how it is implemented in the editor).
