### ISSUE TITLE
How to finish the DataTypeConvert function to make rules work well?

### ISSUE THREAD

**Issue by zorc** [microsoft/RulesEngine#249]
Hello, big guys：

I had trouble when I tried to complete the code，I didn't know how to finish the DataTypeConvert function,I need your help,thanks and best regards.

This is ExceptionMessage in RuleResultTree:
Exception while parsing expression `x==0` - The binary operator Equal is not defined for the types 'System.Object' and 'System.Int32'.
Exception while parsing expression `x==true` - The binary operator Equal is not defined for the types 'System.Object' and 'System.Boolean'.

    class Program
    {
        static void Main(string[] args)
        {
            var tr = new TestRule();
            Random ran = new Random();
            int RandKey = ran.Next(0, 2);
            tr.RunTest(RandKey, "int").Wait();
            tr.RunTest(RandKey, "bool").Wait();
        }
    }

    public class TestRule
    {
        public async Task RunTest(object value, string type)
        {
            var colorRules = InitColorRules();
            List<Rule> rules = new List<Rule>();
            foreach (var colorRule in colorRules)
            {
                Rule rule = new Rule();
                rule.RuleName = colorRule.Color;
                rule.Expression = colorRule.Rule;
                rule.RuleExpressionType = RuleExpressionType.LambdaExpression;
                rules.Add(rule);
            }
            var workflows = new List<Workflow>();
            Workflow workflow = new Workflow();
            workflow.WorkflowName = "ExampleWorkflow";
            workflow.Rules = rules;
            workflows.Add(workflow);
            var re = new RulesEngine.RulesEngine(workflows.ToArray(), null);
            var input = new RuleParameter("myInput", new
            {
                x = DataTypeConvert(type, value)
            });
            var resultList = await re.ExecuteAllRulesAsync("ExampleWorkflow", input);
            var result = resultList.Where(x => x.IsSuccess).FirstOrDefault();
            if (result != null)
            {
                //Always null
                var color = result.Rule.RuleName;
                Console.WriteLine("value is " + value + "\n result is " + color);
            }
        }

        public dynamic DataTypeConvert(string typeString, object value)
        {
            switch (typeString)
            {
                case "bool":
                    return Convert.ToBoolean(value);
                default:
                    return Convert.ToInt32(value);
            }
        }

        public List<ColorRule> InitColorRules()
        {
            var colorRules = new List<ColorRule>();
            var rule1 = new ColorRule()
            {
                Color = "#FF0000",
                Rule = "x==0"
            };
            colorRules.Add(rule1);
            var rule2 = new ColorRule()
            {
                Color = "#00FF00",
                Rule = "x==1"
            };
            colorRules.Add(rule2);
            var rule3 = new ColorRule()
            {
                Color = "#F00000",
                Rule = "x==true"
            };
            colorRules.Add(rule3);
            var rule4 = new ColorRule()
            {
                Color = "#00000F",
                Rule = "x==false"
            };
            colorRules.Add(rule4);
            return colorRules;
        }
    }

    public class ColorRule
    {
        public string Color { get; set; }
        public string Rule { get; set; }
    }
}

**Comment by abbasc52** [comment]
Hi @zorc ,

Is there any specific reason you need to support both bool and int for same input?
It would still fail for some rules where there is type mismatch

but if you want to set type of x dynamically, why not use generic instead?

``` c#
class Program
{
    static void Main(string[] args)
    {
        var tr = new TestRule();
        Random ran = new Random();
        int RandKey = ran.Next(0, 2);
        tr.RunTest<int>(RandKey).Wait();
        tr.RunTest<bool>(RandKey).Wait(); // you might need to cast to boolean here
    }
}

public class TestRule
{
    public async Task RunTest<T>(T value)
    {
        var colorRules = InitColorRules();
        List<Rule> rules = new List<Rule>();
        foreach (var colorRule in colorRules)
        {
            Rule rule = new Rule();
            rule.RuleName = colorRule.Color;
            rule.Expression = colorRule.Rule;
            rule.RuleExpressionType = RuleExpressionType.LambdaExpression;
            rules.Add(rule);
        }
        var workflows = new List<Workflow>();
        Workflow workflow = new Workflow();
        workflow.WorkflowName = "ExampleWorkflow";
        workflow.Rules = rules;
        workflows.Add(workflow);
        var re = new RulesEngine.RulesEngine(workflows.ToArray(), null);
        var input = new RuleParameter("myInput", new
        {
            x = value
        });
        var resultList = await re.ExecuteAllRulesAsync("ExampleWorkflow", input);
        var result = resultList.Where(x => x.IsSuccess).FirstOrDefault();
        if (result != null)
        {
            //Always null
            var color = result.Rule.RuleName;
            Console.WriteLine("value is " + value + "\n result is " + color);
        }
    }

    public List<ColorRule> InitColorRules()
    {
        var colorRules = new List<ColorRule>();
        var rule1 = new ColorRule()
        {
            Color = "#FF0000",
            Rule = "x==0"
        };
        colorRules.Add(rule1);
        var rule2 = new ColorRule()
        {
            Color = "#00FF00",
            Rule = "x==1"
        };
        colorRules.Add(rule2);
        var rule3 = new ColorRule()
        {
            Color = "#F00000",
            Rule = "x==true"
        };
        colorRules.Add(rule3);
        var rule4 = new ColorRule()
        {
            Color = "#00000F",
            Rule = "x==false"
        };
        colorRules.Add(rule4);
        return colorRules;
    }
}

public class ColorRule
{
    public string Color { get; set; }
    public string Rule { get; set; }
}
}
```

**Comment by zorc** [comment]
Hi @abbasc52 
In my business scenario, the user's input comes from JavaScript, and he will bring the data type in JSON, like this:
```
[
{
'name':'x',
‘type’:'int',
'value':'1',
'number':1
},
{
'name':'x',
‘type’:'bool',
'value':'1',
'number':2
}
]
```
and the 'type' field content include: int、long、string、date、datetime 、timestamp、bool
So I have to convert the data type according to the input, and output color result by rule.
This is how I deal with this problem now, but it doesn't look good，so I want to turn it into a function:
```
var input = new RuleParameter("myInput", new
                    {
                        x = value
                    });
                    switch (schema)
                    {
                        case "bool":
                            input = new RuleParameter("myInput", new
                            {
                                x = Convert.ToBoolean(value)
                            });
                            break;
                        case "int":
                            input = new RuleParameter("myInput", new
                            {
                                x = Convert.ToInt32(value)
                            });
                            break;
                        case "long":
                            input = new RuleParameter("myInput", new
                            {
                                x = Convert.ToInt64(value)
                            });
                            break;
                        case "timestamp":
                            input = new RuleParameter("myInput", new
                            {
                                x = Convert.ToInt64(value)
                            });
                            break;
                        case "float":
                            input = new RuleParameter("myInput", new
                            {
                                x = Convert.ToDecimal(value)
                            });
                            break;
                        case "double":
                            input = new RuleParameter("myInput", new
                            {
                                x = Convert.ToDecimal(value)
                            });
                            break;
                        case "date":
                            input = new RuleParameter("myInput", new
                            {
                                x = Convert.ToDateTime(value)
                            });
                            break;
                        case "datetime":
                            input = new RuleParameter("myInput", new
                            {
                                x = Convert.ToDateTime(value)
                            });
                            break;
                        default:
                            input = new RuleParameter("myInput", new
                            {
                                x = Convert.ToString(value)
                            });
                            break;
                    }
```
thanks and best regards.
