### ISSUE TITLE
Couldn't find If I can to make some interaction between workflows

### ISSUE THREAD

**Issue by iagoshavidze1** [microsoft/RulesEngine#257]
I am interested if I can to make dependency between workflows?
So, I have many workflows and one input, I want to have some conditions between worflows.

**Comment by abbasc52** [comment]
Hi @iagoshavidze1 ,

Thanks for the detailed example, we did start with building this kind of interaction. However, it is in early phase and i would not recommend directly using it.

You can build your own action using this as a reference - https://github.com/microsoft/RulesEngine/blob/main/src/RulesEngine/Actions/EvaluateRuleAction.cs

The main part that it is missing is passing additional inputs from existing rule.

**Comment by abbasc52** [comment]
I am planning to add this kind of integration but i am unable to give too much time this. If you are interested you develop your own custom action and contribute it to the project 😄

**Comment by abbasc52** [comment]
This feature is available as a part version 3.5.0
