### ISSUE TITLE
Return all outcomes of the rules for a single row of data

### ISSUE THREAD

**Issue by glagace** [microsoft/RulesEngine#27]
I was hoping to use the engine to validate fields in a class to determine if all fields passed a set of rules. An example would be is the length of field 1 is > 2, another rule would be the value of field 2 is > 5. I was hoping that if rule 2 failed then I would be able to capture it on the OnFail method. It seems that if rule 1 passes it does not call the OnFail method for rule 2,  Is this the correct behavior? 

 Here is a sample rule.
```json
[
  {
    "WorkflowName": "NonEdi_Header",
    "Rules": 
	[
      {
        "RuleName": "lengthrule",
        "SuccessEvent": "10",
        "ErrorMessage": "wut",
        "ErrorType": "Error",
        "RuleExpressionType": "LambdaExpression",
        "Expression": "input1.ClaimCode == \"300065847701\" "
		},
       {
        "RuleName": "classid",
        "SuccessEvent": "100",
        "ErrorMessage": "Case id not equal 1 ",
        "ErrorType": "Error",
        "RuleExpressionType": "LambdaExpression",
        "Expression": "input1.ClientId  == \"12\" "
      }
    ]
  }
]
```

**Comment by abbasc52** [comment]
Hi @glagace  
Currently onFail executes only when all rules fail:
https://github.com/microsoft/RulesEngine/blob/13f0912d7c6668fe3038d9034bfb2d3441ad338b/src/RulesEngine/RulesEngine/Extensions/ListofRuleResultTreeExtension.cs#L28-L34

You can write a small code to find what has failed:
```csharp
result.Where(ruleResult => ruleResult.IsSuccess == false).Select(ruleResult => ruleResult.SuccessEvent)
```

**Comment by glagace** [comment]
thank you for your quick response, I believe I created something similar to capture a list of records that passed all rules and a list of rules that failed.

  if (resultList.Count(item => item.IsSuccess == false) > 0)
                    {
                        foreach (RuleResultTree value in resultList.FindAll(element => element.IsSuccess == false))
                        {
                            falserules.Add(value);
                        }
                    }
                    else
                    {
                        successrules.Add(resultList.Find(element => element.IsSuccess == true));
                    }
