### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by neil-119** [microsoft/RulesEngine#273]
Hello, I have a question about the security aspect of library. If we wanted to use this to give end-users the ability to define their own business rules, what is the possibility of a potential injection attack on other parts of the system? What are some steps that we can take to mitigate it? Thanks.

**Comment by alexreich** [comment]
@neil-119, this library does not handle security. In terms of the the [Rules Engine Editor](https://github.com/alexreich/RulesEngineEditor/), you can roll your own. In my own use case, we set up roles using Active Directory so only certain users had access to defining the rules at all. Depending on your storage (file or database), you may consider the same.

**Comment by abbasc52** [comment]
@neil-119 , RulesEngine only exposes the classes or types that are registered by developer. In that aspect, as long as you don't expose a class or type which can lead to a potential attack it will work fine. (E.g. File reader, db connection)

My recommendation would be wrapping such sensitive operations inside a custom class and using it in RulesEngine.
That way you could follow the same dotnet security practices.
