### ISSUE TITLE
decimal null check returns True when comparing with 0

### ISSUE THREAD

**Issue by DarkRa** [microsoft/RulesEngine#279]
Hello,

In rule I'm trying to check if the value is null and it returns IsSuccess = true even if value set as (decimal?)0.

Here's an example: https://dotnetfiddle.net/bTT3pA
```
new Rule { RuleName = "Rule1", Expression = "Number == null" },
new Rule { RuleName = "Rule2", Expression = "Number == 0" }
```
Both of them will return IsSuccess = true. But I expect that Rule1 should return false instead.

**Comment by alexreich** [comment]
@DarkRa, this is likely a limitation of [Dynamic LINQ](https://dynamic-linq.net/). Use `Number is null` instead.

Working example: https://dotnetfiddle.net/cPGUMH

**Comment by DarkRa** [comment]
@alexreich Thanks for suggestion, but in this case it will fail if I will pass number as null.

Here is an example: https://dotnetfiddle.net/T6eEwz

I make it work with changing this line: 
https://github.com/microsoft/RulesEngine/blob/65d2abbd8b28d631a7a886b2ad3760641423eb80/src/RulesEngine/ExpressionBuilders/RuleExpressionParser.cs#L54

To this one:
`return wrappedExpression.Compile();`

To use method from regular System.Linq.Expressions instead of using FastExpressionCompiler.
But not sure yet how it will affect on performance.

**Comment by alexreich** [comment]
@DarkRa, I've corrected the expression to account for nulls using `Object.ReferenceEquals(null, Number)`: https://dotnetfiddle.net/cPGUMH.

Keep in mind, for exotic transformation evaluations, you can always pass a class into [ReSettings ](https://github.com/microsoft/RulesEngine/wiki/Getting-Started#resettings)

**Comment by abbasc52** [comment]
HI @DarkRa , The expression language used in RulesEngine is Dynamic Linq as @alexreich  mentioned.
Although the language rules are mostly similar to C#, it does have a few constructs which are similar sql linq.
So `value == null` might fail. 

You can refer the expression language here - https://dynamic-linq.net/expression-language
