### ISSUE TITLE
Runnable sample app

### ISSUE THREAD

**Issue by KoalaBear84** [microsoft/RulesEngine#28]
The sample app provided in this repository is quite difficult to get running.

When you open it (the csproj), it already begins complaining about the missing SDK or framework:
![image](https://user-images.githubusercontent.com/5886900/86515834-32de1b80-be1c-11ea-8639-a38882883a4d.png)

I think it is because it is not part of a solution. But even when you add it to a solution already containing a .NET Core Console App you run into more problems. And that is the missing nuget package(s). Also, it is not possible to add them, because it somehow does not understand it.

So. Take 3, copying over the files to the current console app. Even that did not automatically work. It complains about multiple entry points in the project. So I had to even change more things to get it working.

Also there is too little info about building a (dynamic) input, without JSON as the 'input' for the inputs.

I finally found out. Please provide a full out-of-the-box working example app. Thanks!

Also there is no info about the "Operator" property, I guess it is not implemented/used? Also some more info about the inputs would be nice. What type is expected? Would be nice if that info is also on the readme/wiki, and not only in the example app.

**Comment by KoalaBear84** [comment]
Hmm, I see I also get this when opening the main RulesEngine.sln, probably because of the `global.json` containing `"version": "3.1.101"`, when I change it to "version": "3.1.301" (current version on https://dotnet.microsoft.com/download) it works. Is it targetted to a too specific version?

If so, please add something like `"rollForward": "latestFeature"` or `"rollForward": "latestMajor"`, or remove global.json and replace it with the normal targets like ".NET Core 3.1" etc.

https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x

**Comment by abbasc52** [comment]
HI @KoalaBear84 , Thanks for raising this issue. we will add `"rollForward": "latestFeature"` to resolve this. We can't remove global.json as dotnet core sdk sometimes shows conflicts when multiple versions are installed
