### ISSUE TITLE
Array elements only contain properties that exist on first item

### ISSUE THREAD

**Issue by MariusJaskunas** [microsoft/RulesEngine#285]
Hello,

I encountered a problem while trying run validation for Array. It seems, that RuleEngine converts all array elements to the format of first elements. If following elements have more properties, then those are not available in rule expression.

Example input:
```
dynamic exp1 = new ExpandoObject();
exp1.Name = "EXP1";
dynamic exp2 = new ExpandoObject();
exp2.Name = "EXP2";
exp2.Date = DateTime.Now;

dynamic expando = new ExpandoObject();
expando.list = new List<ExpandoObject>
{
    exp1,
    exp2
};
```

**Actual result:**
After debugging, I get these values as inputs of rule:

![image](https://user-images.githubusercontent.com/24454682/144629045-05b8d50f-4338-4b84-9e13-8a46a12b0876.png)

**Expected result:**
Second element will contain Date property.

**Notes:**
If I change array items to JObject, then this problem does not appear.
![image](https://user-images.githubusercontent.com/24454682/144629835-3f96ae46-01a5-454f-9fc3-12781cc1006f.png)

Package version: 3.0.2. Same with 3.4.0.
I would like to know if I can make it work with ExpandoObjects or I should switch to other types.

**Comment by MariusJaskunas** [comment]
After looking around the code, it seems that the issue is caused by this line:
https://github.com/microsoft/RulesEngine/blob/65d2abbd8b28d631a7a886b2ad3760641423eb80/src/RulesEngine/HelperFunctions/Utils.cs#L51

**Comment by MariusJaskunas** [comment]
I tried to solve problem myself, unfortunately, there are few problems. This is the draft PT
https://github.com/microsoft/RulesEngine/pull/286

**Comment by abbasc52** [comment]
Hi Maruis, There are some limitations when converting nested dynamic items. One workaround is to use a typed object as it gives you more control over which properties are surfaced.
We could run through the list to get all available properties but that would result in a performance impact. It is better to use a typed object in this scenario.

**Comment by MariusJaskunas** [comment]
Understandable. It would be good to provide information about such limitation in documentation.

Closing ticket, understandable that it is not worth doing it.
