### ISSUE TITLE
Feature request, Export  rule into SQL select statement

### ISSUE THREAD

**Issue by mrs01dev** [microsoft/RulesEngine#287]
Please ,
If possible ,create an exporter to  covert rule into SQL select statement.
Within an application ,end users can compose  a rule and then have data come back from MS SQL server 
Thanks

**Comment by abbasc52** [comment]
Hi @mrs01dev,

I am not sure if i understand your use case correctly, but RulesEngine converts rules to runnable C# code.

If you are looking for calling database and use it in Rules, use EFcore for connecting to sql and pass `IQueryable` as input to RulesEngine.

If you are looking for something else, please provide additional information and a sample of what you expect the RulesEngine to do.
