### ISSUE TITLE
Using RuleParameter have strange effect

### ISSUE THREAD

**Issue by KoalaBear84** [microsoft/RulesEngine#29]
I like the idea of having an engine that can parse expressions like we are used to in C#!

But I see that the RuleParameter, which anybody should use to have the right input names in the expression is causing problems, and I don't have any idea why it is not behaving as expected.

**Example program:**
```csharp
class Program
{
	static void Main(string[] args)
	{
		Console.WriteLine("Started!");

		Sample1();
		Sample2();
		Sample3();
		Sample4();
		Sample5();
		Sample6();

		Console.WriteLine("Finished!");
		Console.ReadKey(intercept: true);
	}

	public static void Sample1()
	{
		RulesEngine.RulesEngine rulesEngine = GetRulesEngineWithRules();

		dynamic entity = new ExpandoObject();
		entity.Field1 = "Value1";
		entity.Field2 = 10;

		List<RuleResultTree> resultList = rulesEngine.ExecuteRule("Workflow", entity);

		ShowResult("Sample1 (ExpandoObject, no RuleParam)", resultList);
	}

	public static void Sample2()
	{
		RulesEngine.RulesEngine rulesEngine = GetRulesEngineWithRules();

		dynamic entity = new ExpandoObject();
		entity.Field1 = "Value1";
		entity.Field2 = 10;

		List<RuleResultTree> resultList = rulesEngine.ExecuteRule("Workflow", new RuleParameter("input1", entity));

		ShowResult("Sample2 (ExpandoObject, RuleParam)", resultList);
	}

	public static void Sample3()
	{
		RulesEngine.RulesEngine rulesEngine = GetRulesEngineWithRules();

		Dictionary<string, object> entity = new Dictionary<string, object>
		{
			{ "Field1", "Value1" },
			{ "Field2", 10 }
		};

		List<RuleResultTree> resultList = rulesEngine.ExecuteRule("Workflow", entity);

		ShowResult("Sample3 (Dictionary<string, object>, no RuleParam)", resultList);
	}

	public static void Sample4()
	{
		RulesEngine.RulesEngine rulesEngine = GetRulesEngineWithRules();

		Dictionary<string, object> entity = new Dictionary<string, object>
		{
			{ "Field1", "Value1" },
			{ "Field2", 10 }
		};

		List<RuleResultTree> resultList = rulesEngine.ExecuteRule("Workflow", new RuleParameter("input1", entity));

		ShowResult("Sample4 (Dictionary<string, object>, RuleParam)", resultList);
	}

	public static void Sample5()
	{
		RulesEngine.RulesEngine rulesEngine = GetRulesEngineWithRules();

		ExpandoObject entity = new ExpandoObject();
		IDictionary<string, object> dictionary = entity;
		dictionary.Add("Field1", "Value1");
		dictionary.Add("Field2", 10);

		List<RuleResultTree> resultList = rulesEngine.ExecuteRule("Workflow", entity);

		ShowResult("Sample5 (ExpandoObject filled through Dictionary<string, object>, no RuleParam)", resultList);
	}

	public static void Sample6()
	{
		RulesEngine.RulesEngine rulesEngine = GetRulesEngineWithRules();

		ExpandoObject entity = new ExpandoObject();
		IDictionary<string, object> dictionary = entity;
		dictionary.Add("Field1", "Value1");
		dictionary.Add("Field2", 10);

		List<RuleResultTree> resultList = rulesEngine.ExecuteRule("Workflow", new RuleParameter("input1", entity));

		ShowResult("Sample6 (ExpandoObject filled through Dictionary<string, object>, RuleParam)", resultList);
	}

	private static RulesEngine.RulesEngine GetRulesEngineWithRules()
	{
		Rule rule1 = new Rule { RuleName = "Rule1", Expression = "input1.Field1 = \"Value1\"", ErrorType = ErrorType.Error, RuleExpressionType = RuleExpressionType.LambdaExpression };
		Rule rule2 = new Rule { RuleName = "Rule2", Expression = "input1.Field2 > 5", ErrorType = ErrorType.Error, RuleExpressionType = RuleExpressionType.LambdaExpression };
		RulesEngine.RulesEngine rulesEngine = new RulesEngine.RulesEngine(new string[] { }, null);

		rulesEngine.AddWorkflow(new WorkflowRules
		{
			WorkflowName = "Workflow",
			Rules = new List<Rule>
			{
				rule1,
				rule2
			}
		});

		return rulesEngine;
	}

	private static void ShowResult(string name, List<RuleResultTree> resultList)
	{
		Console.WriteLine($"{name}:{Environment.NewLine}{string.Join(Environment.NewLine, resultList.Select(r => $"{r.Rule.RuleName} - {(r.IsSuccess ? r.IsSuccess.ToString() : r.ExceptionMessage)}"))}{Environment.NewLine}");
	}
}
```

**Output:**
```
Sample1 (ExpandoObject, no RuleParam):
Rule1 - True
Rule2 - True

Sample2 (ExpandoObject, RuleParam):
Rule1 - No property or field 'Field1' exists in type 'ExpandoObject'
Rule2 - No property or field 'Field2' exists in type 'ExpandoObject'

Sample3 (Dictionary<string, object>, no RuleParam):
Rule1 - True
Rule2 - Operator '>' incompatible with operand types 'Object' and 'Int32'

Sample4 (Dictionary<string, object>, RuleParam):
Rule1 - True
Rule2 - Operator '>' incompatible with operand types 'Object' and 'Int32'

Sample5 (ExpandoObject filled through Dictionary<string, object>, no RuleParam):
Rule1 - True
Rule2 - True

Sample6 (ExpandoObject filled through Dictionary<string, object>, RuleParam):
Rule1 - No property or field 'Field1' exists in type 'ExpandoObject'
Rule2 - No property or field 'Field2' exists in type 'ExpandoObject'
```

I would have expected that all samples would return true for both rules.

Only changing `List<RuleResultTree> resultList = rulesEngine.ExecuteRule("Workflow", entity);` to `List<RuleResultTree> resultList = rulesEngine.ExecuteRule("Workflow", new RuleParameter("input1", entity));` messes it up. For me as a user I would have expected that it would behave exactly the same, because it already was "input1", and now I explicitly named it like "input1".

And the the `Dictionary<string, object>` (Sample3/4) I would have expected it would understand the underlying types.

Also, please provide some examples of this feature. The main problem using this nice project is the lack of examples.

Thanks in advance!

**Comment by KoalaBear84** [comment]
Hmm.. Just looked at the code and saw a workaround to get it working. But why is it needed? Because when you are not used named parameters (RuleParameter) it does work out of the box. If I use the `Utils.GetTypedObject` it is working. But that is not what you expect from using `RuleParameter`.

`List<RuleResultTree> resultList = rulesEngine.ExecuteRule("Workflow", new RuleParameter("entity", Utils.GetTypedObject(entity)));`

**Comment by KoalaBear84** [comment]
I also see that using this with the `ExpandoObject` is VERY important. If you only use a Dictionary<string, object> it will see all properties as type `Object` and it cannot compare anything.

```csharp
ExpandoObject entity = new ExpandoObject();
IDictionary<string, object> entityValues = entity;

List<RuleResultTree> resultList = rulesEngineEntity.ExecuteRule("Workflow", new RuleParameter("entity", Utils.GetTypedObject(entityValues)));
```

I guess it should also be possible without the ExpandoObject? Like:
```csharp
if (field is decimal decimalValue) {
}
if (field is double doubleValue) {
}
```

**Comment by abbasc52** [comment]
> Hmm.. Just looked at the code and saw a workaround to get it working. But why is it needed? Because when you are not used named parameters (RuleParameter) it does work out of the box. If I use the `Utils.GetTypedObject` it is working. But that is not what you expect from using `RuleParameter`.
> 
> `List<RuleResultTree> resultList = rulesEngine.ExecuteRule("Workflow", new RuleParameter("entity", Utils.GetTypedObject(entity)));`

Agreed, RuleParameter should also handle dynamic objects.Will raise PR for it.


> I also see that using this with the `ExpandoObject` is VERY important. If you only use a Dictionary<string, object> it will see all properties as type `Object` and it cannot compare anything and you will get like these errors:

Currently we support any typed object, anonymous object and dynamic object. We don't support dictionary currently, but it is possible to typecast it to ExpandoObject and get it working.

**Comment by KoalaBear84** [comment]
Thanks, great! If possible, it would be nice if some sample code could be added for the dictionary.

**Comment by abbasc52** [comment]
Hi @KoalaBear84 , we thought over decided to not support dictionary to object conversion for now as it may lead to other issues for people who want to use dictionary 'as is' in expression. You can still use all the features with typed/anonymous/dynamic object.

**Comment by KoalaBear84** [comment]
That is also an answer :)

It would be good to document more about the RuleParameter and what you can or should pass to it, and also add examples about it in the sample app. And also mention an example with a Dictionary, that would be great!

So when passing a dictionary you could do like `item["property"] == "value"`? And when you do what I did and use the `Utils.GetTypedObject(dictionary)` it would still work as expected.
