### ISSUE TITLE
Or, OrElse, And, AndAlso

### ISSUE THREAD

**Issue by poostwoud** [microsoft/RulesEngine#296]
Looking at the code it seems Or and OrElse are synonyms, as well as And and AndAlso. Is this correct?

**Comment by IainAdamsLabs** [comment]
Could we have some documentation on usage of these operators please?

**Comment by IainAdamsLabs** [comment]
> Could we have some documentation on usage of these operators please?

Likewise, it would be nice to have documentation on Success Events and Errors. There is a section on OnSuccess and OnFail but I can't find any documentation on these schema fields: SuccessEvent, ErrorMessage, ErrorType.

**Comment by abbasc52** [comment]
> Looking at the code it seems Or and OrElse are synonyms, as well as And and AndAlso. Is this correct?

Yes, since rules are always boolean, they are synonyms

**Comment by skuehlshelby** [comment]
This seems somewhat confusing. In VB.NET, Or and And are bit-wise operators equivalent to C#'s | and &. I had expected that they would not be synonymous, but would instead perform bit-wise operations.

**Comment by abbasc52** [comment]
Hi @skuehlshelby Or and And are indeed bitwise operation, but when considering rules which always result in boolean,
true & true is equivalent to true && true and true | false is equivalent to true || false.

**Comment by vamsidogiparthi** [comment]
To get some insights into the usage and documentation of these operators.

https://medium.com/@vamsidogiparthi/understanding-ms-rules-engine-nested-rules-part-5-36439b25291c
