### ISSUE TITLE
No applicable method '<method>' exists in type '<static class>'

### ISSUE THREAD

**Issue by jpaterson-vdc** [microsoft/RulesEngine#3]
var bre = new RulesEngine.RulesEngine(workflowRules.ToArray(), null, new ReSettings { CustomTypes = new Type[] { typeof(AppHelpers) } });

When using CustomTypes, the LambdaExpressionBuilder generates an error when calling the ParseLambda method.  The AppHelpers class is a public, static class and the methods in the class are all declared static just as it explains in the Wiki.  There are some instances where I was able to get this to work, but most of the time it failes with the error message in the header of this issue post.

**Comment by dishantmunjal** [comment]
Hi @jpaterson-vdc 
Could you please share an example method for which it failed so that we can repro the bug?

**Comment by abbasc52** [comment]
Closing this issue as OP has not responded yet. @jpaterson-vdc  feel free to reopen it if you are still facing this issue

**Comment by denys-holdun** [comment]
Hi @abbasc52  
Faced same issue 
No applicable aggregate method 'GetM()' exists

Static class
```
public static class Test
  {
        public const string T = "test";

        public static string GetM(this List<string> p) => String.Join(',', p);
  }
```
    
```
    var bre = new RulesEngine.RulesEngine(workflowRules.ToArray(), null, new ReSettings
            {
                CustomActions = new Dictionary<string, Func<ActionBase>>
                {
                    {nameof(CustomAction), () => new CustomAction()}
                },
                CustomTypes = new []{ typeof(Test) },
                
            });
```

Json
 
![image](https://user-images.githubusercontent.com/74546642/140742774-4672006e-8c1e-46b6-8fe4-81178d5d78af.png)
![image](https://user-images.githubusercontent.com/74546642/140742839-42ee3ab9-2728-4415-95ec-66d45d9c5a28.png)
![image](https://user-images.githubusercontent.com/74546642/140742556-663de9aa-12b0-484d-8b89-7850587317d0.png)

**Comment by jporr** [comment]
same problem here, extension methods do not seem to work even when adding them to CustomTypes list

**Comment by dev-santosh** [comment]
public static bool MustBeActive(int Id)
{
    return Id == 1;
}
Above one is not working.

where as
this one is working
public static bool MustBeActive(Int32 Id)
{
    return Id == 1;
}

Strange???
