### ISSUE TITLE
Request to add ErrorMessage/SuccessEvent parameters

### ISSUE THREAD

**Issue by maTraxion** [microsoft/RulesEngine#302]
For a rule's Expression it's possible to pass in parameters. It would be great if this were possible for SuccessEvent/ErrorMessages for generic rules.

For instance let's imagine we used the RulesEngine to validate Animals as the generic, with Cats and Dogs being specific types. A rule might be that both Cats and Dogs need a name property. For this purpose it would be great to write a generic rule, with the SuccessEvent returning resulting in "The {animal.type} contains the mandatory name property".

**Comment by abbasc52** [comment]
Hi @maTraxion SuccessEvent was meant to be a simple static output. If you are looking for advance usage, you should be able to achieve it with output expression action-  https://microsoft.github.io/RulesEngine/#outputexpression

**Comment by maTraxion** [comment]
@abbasc52 I assume this solution will fix my issue, I'll close this issue for now and reopen it if this isn't quite what I'm looking for. Thanks for the tip!
