### ISSUE TITLE
Lambda Expression DateTime comparison

### ISSUE THREAD

**Issue by davebrannan** [microsoft/RulesEngine#305]
Hi,

Should DateTime expressions work out of the box? 

I'm trying with an expression like "Expression": "input1.Date => \"2022-01-24T15:36:49.8219139Z\"" (which is ISO 8601 UTC format) but its not firing.

**Comment by abbasc52** [comment]
Hi @davebrannan , RulesEngine does not automatically convert Datetime.
You might want to parse it yourself
```DateTime.Parse(\"2022-01-24T15:36:49.8219139Z\")```

Also i assume you wanted to to use `>=` and not `=>`

**Comment by davebrannan** [comment]
Hi @abbasc52 . I thought the parsing/date comparison was done inside the engine, do you have an example of where to put the above command? 

Thanks!

**Comment by davebrannan** [comment]
Actually, to be clear, I want to have rules supporting time of the day like "input1.Time => "17:00"".

Is there a way to tell the RulesEngine how a field in the json is to be compared? Or does it only support string and int?

**Comment by abbasc52** [comment]
@davebrannan , can you clarify what `input1.Time => "17:00"` is expected to do?

**Comment by davebrannan** [comment]
Sure. I want to support flexible rules based on dates and times. For example rules like:

input1.Time => "17:00" is "rule is success and action invoked if time of day is after 5pm"
input1.Time => "05:00" AND input1.Time <= "10:00" is "rule is success and action invoked if time of day is between 5am and 10am"
input1.Date => "30/01/2022 15:00:00" AND <= "05/02/2022 15:00:00" is "rule is success and action invoked if date is between 30th and 5th at 3pm"

etc. Hope that makes sense. Basically the inputs are "events" that have multiple properties, one of which is a datetime, and I want to allow the creation of rules based on the datetime field.

**Comment by abbasc52** [comment]
Thanks for the explanation.

First if you are using dynamic input (not mapped to any class) then `input1.Date` and `input1.Time` might be string type 
To convert them you could use `DateTime.Parse` so for example:
input1.Time <= "17:00"
would be represented as:
`DateTime.Parse(input1.Time) <= DateTime.Parse("17:00")`

if Time is already a DateTime obj, you can just do it for the other string.
`input1.Time <= DateTime.Parse("17:00")`

**Comment by davebrannan** [comment]
Ah, so it's in the json "expression" field itself that I can do the parsing?

**Comment by abbasc52** [comment]
Yes it supports most of c# constructs in it. You can even create custom classes and use it in expression.

You can find most details here: https://microsoft.github.io/RulesEngine

**Comment by davebrannan** [comment]
At that page I see "Extending expression via custom class/type injection" at the top of the page but doesn't look like there is content for it yet.

**Comment by abbasc52** [comment]
@davebrannan I will be closing this issue since original issue is resolved. For any documentation related issues, please mention it in  #103
