### ISSUE TITLE
Support for case (in)sensitivity

### ISSUE THREAD

**Issue by maTraxion** [microsoft/RulesEngine#308]
I use the RulesEngine to validate whether a given response contains certain attributes. The attribute names however must be case insensitive. If I receive a product with a Name attribute it must be handled the same as name, nAmE, etc. 
`"input1.Name != null"` 
Must for my project be treated the same as:
`"input1.name != null"`

Is there any existing solution for this issue?

**Comment by abbasc52** [comment]
case insensitivity is already supported by rulesEngine

**Comment by maTraxion** [comment]
I'm afraid the documentation doesn't make it very clear for me how to use/enable it, as it doesn't seem to be enabled by default. Could you tell me on which page of the documentation I can find more information on this @abbasc52 ?

**Comment by abbasc52** [comment]
@maTraxion it is enabled by default. Internally we use dynamic.linq.core for expression parsing which is case insensitive by default. We also have a test case to validate this.

If you are facing issue, can you provide an example on https://dotnetfiddle.net/ ? I can have a look.
