### ISSUE TITLE
Ability to check rules without Workflow

### ISSUE THREAD

**Issue by KoalaBear84** [microsoft/RulesEngine#31]
It would be nice to check for a single rule.

```csharp
private static void Sample1()
{
	RulesEngine.RulesEngine rulesEngine = new RulesEngine.RulesEngine(new string[] { }, null);

	dynamic entity = new ExpandoObject();
	entity.Field1 = "Value1";
	entity.Field2 = 10;

	Rule rule1 = new Rule { RuleName = "Rule1", Expression = "input1.Field1 = \"Value1\"", ErrorType = ErrorType.Error, RuleExpressionType = RuleExpressionType.LambdaExpression };
	RuleResultTree ruleResult = rulesEngine.ExecuteRule(rule1, entity);
}
```

Also, it looks like `ExecuteRule` actually should be named `ExecuteWorkflow`, and that we should have a real ExecuteRule you can supply a Rule to which returns true/false or RuleResultTree :)

My current workaround is just adding a workflow with the name of "Workflow" and call it with `rulesEngine.ExecuteRule("Workflow", entity)`

**Comment by abbasc52** [comment]
@KoalaBear84 are you looking for Rule Evaluation or just Expression evaluation? As a part of recent changes, we are planning to expose our rule processor so you can evaluate an expression outside RulesEngine

**Comment by KoalaBear84** [comment]
That would be great.

The main thing I use is see if the entity/object matched the rules. I don't know if that is Rule Evaluation or Expression Evaluation? :)

**Comment by glagace** [comment]
Has this been implemented?

**Comment by abbasc52** [comment]
@glagace @KoalaBear84, this is available in v3 preivew. You can use [RuleExpressionParser](https://github.com/microsoft/RulesEngine/blob/master/src/RulesEngine/ExpressionBuilders/RuleExpressionParser.cs) to evaluate an expression.

**Comment by KoalaBear84** [comment]
Thanks @abbasc52 

Do you have an example of the usage of the RuleExpressionParser?

Something like this? (I see there is no RuleResultTree thing, so I'm lost) :) Or is it meant for something else?

```csharp
RuleExpressionParser ruleExpressionParser = new RuleExpressionParser(new ReSettings());
List<RuleResultTree> resultList = ruleExpressionParser.Evaluate("entity.BooleanField == true", new RuleParameter("entity", entityValues));
```

**Comment by abbasc52** [comment]
it is just a parser so it will return u the result of expression. Also it is not limited to boolean expressions 😄 
In your case it should be:
```c#
RuleExpressionParser ruleExpressionParser = new RuleExpressionParser(new ReSettings());
object output = ruleExpressionParser.Evaluate("entity.BooleanField == true", new RuleParameter("entity", entityValues));
if((bool)output){

}
```

**Comment by KoalaBear84** [comment]
OK, would this also work?

```csharp
RuleExpressionParser ruleExpressionParser = new RuleExpressionParser(new ReSettings());
object output = ruleExpressionParser.Evaluate("entity.stringField == \"test\"", new RuleParameter("entity", entityValues));
if((bool)output){

}```

**Comment by abbasc52** [comment]
yes
