### ISSUE TITLE
workflow-schema.json file not up-to-date

### ISSUE THREAD

**Issue by rajeev-ayer** [microsoft/RulesEngine#310]
The current version of the file [workflow-schema.json](https://github.com/microsoft/RulesEngine/blob/main/schema/workflow-schema.json) does not seem up-to-date.  I say this as it does not contain definitions for properties such as `GlobalParams` or `LocalParams`, among others.

This is a useful schema document to help prepare workflow JSON files and would be good to have it updated.

**Comment by felipeogarcia** [comment]
Second that. Also having issues on "WorkFlowName" with that upper case letter "F".
