### ISSUE TITLE
Stop rules from executing with And operator

### ISSUE THREAD

**Issue by tej-rana** [microsoft/RulesEngine#319]
If say a rule is checking for nested object to exist and then another rule is accessing a property in the child object, it should return with the first rule failing to not just prevent throwing exceptions but also to make it run faster.

**Comment by tej-rana** [comment]
I found my answer.
```
  var bre = new RulesEngine.RulesEngine(workflowRules.ToArray(), null, new ReSettings
                {
                    NestedRuleExecutionMode = NestedRuleExecutionMode.Performance
                });
```
This should be added to the docs. But why not make this the default mode?

**Comment by abbasc52** [comment]
Hi @tej-rana , would you mind helping with adding it in our docs ?
We maintain latest docs here -https://github.com/microsoft/RulesEngine/blob/main/docs/index.md

As for why it is not default, Performance mode was added later and we didn't want to introduce a breaking change to existing users
