### ISSUE TITLE
Wiki - Rules Schema has a broken link

### ISSUE THREAD

**Issue by zacharysproul** [microsoft/RulesEngine#332]
`Rules schema is available in the [schema file](https://github.com/microsoft/RulesEngine/blob/master/schema/workflowRules-schema.json). The workflow rules are how we store the rules in the system. ... `

Current URL
`https://github.com/microsoft/RulesEngine/blob/master/schema/workflowRules-schema.json`

Proposed URL
`https://github.com/microsoft/RulesEngine/blob/main/schema/workflow-schema.json`

It may be that the entire wiki needs to be reviewed to change "master" to "main" for URLs.

**Comment by abbasc52** [comment]
Fixed wiki links to point to main
