### ISSUE TITLE
How to return new anonymous types on action result

### ISSUE THREAD

**Issue by koosala** [microsoft/RulesEngine#337]
Hi, to start, thanks! I have been evaluating the rules engine the last few days and it with its use of dynamic linq, appears quite powerful and allows us to harness C# expressions to quite a degree.

There was a particular case I couldn't resolve without fiddling with the rule engine source a bit. 

Use case: a JSON deserialized to an expandoobject is supplied to the rule engine along with the workflow file content. 
input content:
`      {
        "source": {
          "action": "rowAdded",
          "tableId": "a0c5d840-33a9-4aee-9a6a-2dfa5402e13c",
          "templateId": "d7b95e5e-5624-49b5-b221-31314ef8b6e7",
          "group": "blue"
        },
        "target": {
          "table": {
            "templateId": "29b4e7b7-7b85-4603-ab03-e4861328cfc4",
            "group": "blue",
            "tableId": "a0c5d840-33a9-4aee-9a6a-2dfa5402e13c"
          }
        }
      }
`

rule:
`       {
        "RuleName": "AddStepRows",
        "Expression": "target.table.templateId == \"29b4e7b7-7b85-4603-ab03-e4861328cfc4\"",
        "SuccessEvent": "{ \"action\": \"addRows\", \"values\": { \"count\" : 2 } }",
        "Actions": {
          "OnSuccess": {
            "Name": "OutputExpression",
            "Context": {
              "Expression": "target.table.group"
            }
          }
        }
      }
`

Running the above with ExecuteallRulessAsync gets a successful rule result with the SuccessEvent set to the defined string and the ActionResult.Output set to `blue`.

The SuccessResult, as I understand it, needs to be pre-defined string and cannot contain expression or rule evaluation. For any expression evaluation on result, the Actions structure must be defined. That feels like an acceptable and workable approach for our use case. 

if I change the actions to the following:
`        "Actions": {
          "OnSuccess": {
            "Name": "OutputExpression",
            "Context": {
              "Expression": "target"
            }
          }
`
the entire target object is returned as an anonymous data type and that's good. 

The limitation I am running into is with making `Actions.OnSuccess.Context.Expression` richer by outputting custom new anonymous data type.
`
        "Actions": {
          "OnSuccess": {
            "Name": "OutputExpression",
            "Context": {
              "Expression": "new ( target.table.group as color )"
            }
          }
`
The above throws exception `no property or field 'color' exists on object`

That is because while dynamic expression supports creating anonymous type like above, the rule engine's `RuleExpressionParser` parses lambda against an `object` type:

`            return DynamicExpressionParser.ParseLambda(config, false, parameters, returnType, expression);
`
As a quick investigation, changing the return type to null allowed the rule to execute and the new anonymous type created and returned. 

I would prefer to not modify the codebase for our use case, for upgradability. 

Can you please suggest if creating new anonymous type with rule execution is possible?

**Comment by abbasc52** [comment]
It seems to be a bug. We may need to set returnType to null if generic type is of type object. 

There are many pending items. I will try fixing it in next release, but it may take some time
