### ISSUE TITLE
EF 'Demo' migration warnings

### ISSUE THREAD

**Issue by asulwer** [microsoft/RulesEngine#369]
add-migration with the EF Demo has a potential issue.  these are the warnings i receive when i add the migration.  i removed duplicate warnings/issues reported.

- Microsoft.EntityFrameworkCore.Model.Validation[10620]
       The property 'Rule.Properties' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.

- Microsoft.EntityFrameworkCore.Model.Validation[10625]
       The foreign key property 'Rule.RuleName1' was created in shadow state because a conflicting property with the simple name 'RuleName' exists in the entity type, but is either not mapped, is already used for another relationship, or is incompatible with the associated primary key type. See https://aka.ms/efcore-relationships for information on mapping relationships in EF Core.

- The foreign key property 'Rule.RuleName1' was created in shadow state because a conflicting property with the simple name 'RuleName' exists in the entity type, but is either not mapped, is already used for another relationship, or is incompatible with the associated primary key type. See https://aka.ms/efcore-relationships for information on mapping relationships in EF Core.

**Comment by edusoccer1121** [comment]
Same issue with the warnings as described by @asulwer.

**Comment by alexreich** [comment]
@abbasc52 - this issue should now be safe to close. 👍
