### ISSUE TITLE
Will scripts be supported in the future? 

### ISSUE THREAD

**Issue by maikebing** [microsoft/RulesEngine#37]
Now, does the rule support expression calculation, will scripts be supported in the future? This makes it easy for customers to write scripts.

**Comment by abbasc52** [comment]
Can you provide example for what you mean by scripts? 
Currently we provide users to inject custom classes to expression via [resettings](https://github.com/microsoft/RulesEngine/wiki/Getting-Started#resettings)
Let me know if you are looking for something else

**Comment by maikebing** [comment]
A more complex calculation, a simple expression is certainly not complete, need to use scripts such as js for processing, and then to evaluate.

**Comment by maikebing** [comment]
When faced with flexible business, operators or users customize scripts to avoid software developers modifying the code and recompiling it!

**Comment by maikebing** [comment]
see also  
https://thingsboard.io/docs/user-guide/rule-engine-2-0/overview/

**Comment by abbasc52** [comment]
@maikebing Thanks for the explanation! Currently we are not planning to support scripts.
The best workaround we have is to create generic methods and registering them via [resettings](https://github.com/microsoft/RulesEngine/wiki/Getting-Started#resettings), so user can use combination of them in expressions and perform complex calculation.

We also introduced a new feature called `localParams` which allows you to use an expression as variable in rules and thereby allowing you to write more complex rules.
