### ISSUE TITLE
Links for Schema files are not working

### ISSUE THREAD

**Issue by ajaypathak** [microsoft/RulesEngine#370]
Links for Schema files are not working
When i try to open https://github.com/microsoft/RulesEngine/blob/main/schema/workflowRules-schema.json, it is showing 
![image](https://user-images.githubusercontent.com/61545/177731972-303036c1-e09b-4b5b-96fc-af79508438e3.png)
Page

**Comment by abbasc52** [comment]
the correct link for schema is - https://raw.githubusercontent.com/microsoft/RulesEngine/main/schema/workflow-schema.json
Where did u get the schema link reference?

**Comment by ajaypathak** [comment]
From https://github.com/microsoft/RulesEngine/ Page.
Looks like the link is working.
