### ISSUE TITLE
Error while compiling rule when the rule contains a raw string

### ISSUE THREAD

**Issue by girlpunk** [microsoft/RulesEngine#381]
When trying to use a rule with a raw string, the following error occurs. For example:

```csharp
DoStuff(@\"long string with a \ in")
```
generates
```
Error while compiling rule `<name>`: No property or field '@' exists in type 'String', in ScopedParam: Value
```

**Comment by abbasc52** [comment]
Hi @girlpunk , RulesEngine uses a lightweight expression evaluator. As such it does not support raw string in Rules.
For more details on supported syntax, please refer - https://dynamic-linq.net/expression-language
