### ISSUE TITLE
How do I register a non static custom type to leverage dependency injection

### ISSUE THREAD

**Issue by vprabhu81** [microsoft/RulesEngine#387]
I have a complex logic to be checked hence I am trying to introduce a Utils which is a non static class so that I can inject few dependencies, However I am not able to do it.

I also tried this option 
https://github.com/microsoft/RulesEngine/issues/378
where you pass a non static utils class as a rule parameter but I get an exception
Exception while parsing expression Utils.CheckContains("1","1") - Unknown identifier 'Utils'

As document do not provide indepth detail on what capabilities are available, if anyone of you were able to calls a custom type which non static it would be of great help

**Comment by abbasc52** [comment]
@vprabhu81 can you share the code of initialization and calling ExecuteRule method when you are getting this error

**Comment by vprabhu81** [comment]
Hi @abbasc52, It looks like an issue from my end. I was able to figure this out. Thank you anyways
