### ISSUE TITLE
Singleton RulesEngine instance or PerRequest instance?

### ISSUE THREAD

**Issue by heavenwing** [microsoft/RulesEngine#401]
I want to wrap RulesEngine in a ASP.NET Core Web API project.
I like to know if I create an independent RulesEngine instance for per http request, and load single one workflow by http request parameter, is there any performance issue?
Or, I should create a singleton RulesEngine instance globally, and load all workflow into this instance?

**Comment by YogeshPraj** [comment]
You can use both approaches but recommended one is having singleton RulesEngine object and having workflow loaded into RulesEngine this will give the best performance as RulesEngine doesnt require to compile same expression again and again.

**Comment by abbasc52** [comment]
@heavenwing, As @YogeshPraj  mentioned, using RulesEngine object as singleton would result in best performance due to the internal caching and compilation mechanism.

**Comment by berkslv** [comment]
I also think a singleton RulesEngine will provide the best performance. But what if my API runs on multiple instances behind a load balancer? If the rules change dynamically, one of the singleton objects will eventually become outdated? Has anyone been looking for a solution to this?
