### ISSUE TITLE
comparing variable

### ISSUE THREAD

**Issue by gd-rvemula** [microsoft/RulesEngine#414]
Is it possible to compare two variables? 
        {
            "RuleName": "CompareTwoVaribles",
            "ErrorMessage": "Variables could not be compared.",
            "ErrorType": "Error",
            "RuleExpressionType": "LambdaExpression",
            "Expression": "**input1.field1 == input.field2**"
        }

**Comment by abbasc52** [comment]
you can compare variables the same way you would do in c# lang. If the types are different, you may need a typecasting before comparing
