### ISSUE TITLE
nuget package more up to date than github?

### ISSUE THREAD

**Issue by asulwer** [microsoft/RulesEngine#417]
latest release on nuget is 4.0.0 but latest release on github is 3.5.0?  what are the differences?  does another repository exist for nuget?

**Comment by abbasc52** [comment]
@asulwer we are no longer releasing package via github packages as we see very low usage.

**Comment by inzi** [comment]
please do - keeping versions in sync maintains confidence in the project.

Noticing the version differences gave me hesitation to test the project until I saw this post.

Thanks!

**Comment by asulwer** [comment]
@abbasc52 if you are not pushing releases via github then you should remove releases to avoid confusion.
OR
how difficult is it to push a release via nuget and github at the same time?  keeping both in sync shouldn't be much trouble?

**Comment by abbasc52** [comment]
We have created the release in github for v4.0.0. We will take care of automating it with the next release.
