### ISSUE TITLE
Dynamic lists of numbers in input data causing rounding errors

### ISSUE THREAD

**Issue by peeveen** [microsoft/RulesEngine#432]
This is a bit of an edge case, but a workaround exists, so the issue isn't really pressing.

Basically, we have a service that receives data (in JSON), creates a `dynamic` from that data, and evaluates rules using that `dynamic` as input data.

The JSON contains arrays of numbers ... they can be integer or floating-point.

If the first item in an array happens to be an integer (e.g. `{ 1, 2.1, -4.2, ... etc ... }`) then the rules engine treats the rest of the values as integers, and rounds them to the nearest integer, causing the rules evaluations (which may say, for example, `data.values.Any(v => v < 3.6)`) to return incorrect results.

The problem seems to be in the `Utils.CreateAbstractClassType` method, where it samples the first element of a list to detect a type.

I can get around it by formatting all values in the JSON as floating point numbers (e.g. `{ 1.0, 2.1, -4.2, ... etc ...}`).

Obviously a dynamic list can contain any mish-mash of types, and there is only so much that can be done to cater for the myriad of scenarios that can arise, but it might be worth checking the whole array to see if all values can be coerced to a compatible type.

**Comment by peeveen** [comment]
I had a go at a "fix" for this. It might be a bit hamfisted.

https://github.com/peeveen/RulesEngine/commit/c7836974a8a891fb0262816424f821dae7e25a0c

**Comment by abbasc52** [comment]
Hi @peeveen, 
Due to certain limitations around using dynamic objects in c# expressions, we have to enforce a type.
The current logic tries to create an anonymous object based on first value (over simplified)

Now if you are sure of the type of object, you could pass a `strongly typed object`, which would skip this process.
Checking for more values can help in certain scenarios but we would need to find a balance between performance and accuracy.

**Comment by peeveen** [comment]
Hi,
Yes, I thought this might be a worry for performance. The data I'm passing to the rules engine comes from raw JSON which is being parsed to a pure dynamic ExpandoObject, so I have no idea of any types in advance. I suppose in the JSON->ExpandoObject parsing code, we could perform a similar coercion process.

**Comment by abbasc52** [comment]
I can think of 2 approaches:
- Check first `N` values (let us say 3-5), which can guarantee performance irrespective of array length
- Allow numbers to be interpreted as `decimal` (this can be made configurable) which should be good for most use cases.

Let me know your thoughts on this.

**Comment by abbasc52** [comment]
> * Check first `N` values (let us say 3-5), which can guarantee performance irrespective of array length

Checking for N values will also require handling specially in case of list of objects with changing fields, in these cases we expect users to use strong types as this logic can't support everything

**Comment by peeveen** [comment]
Forcing decimal would probably break any bitwise operators in expressions, though I suppose if it's configurable, you'll know whether you're going to be using anything like that.
The number of values sampled seems like it might be a decent candidate for configuration ... and allow "0" for "all data"?

I discovered another dynamic problem in the interim ... empty arrays (which will be interpreted as "object" arrays by the `CreateAbstractClassType` code) then cause Dynamic LINQ to fail to parse expressions like `testData.myArray.Any(x => x > 10)`, as it believes the data will be of type `object`, and complains about the `>` operator being used. Attempting to cast the value in the expression (`testData.myArray.Any(x => Int64(x) > 10)`) just generates a different error (Unable to cast object of type 'System.Linq.Expressions.DynamicExpression1' to 'System.Linq.Expressions.ParameterExpression').

Example test code: https://github.com/peeveen/RulesEngine/blob/emptyArrayTest/test/RulesEngine.UnitTest/EmptyCollectionTest.cs

I can't find any way around it. I realise it's probably more of a Dynamic LINQ problem though.

**Comment by peeveen** [comment]
Actually, disregard the empty array thing. I've since discovered the `.Cast("typename")` method in [Dynamic LINQ expression language](https://dynamic-linq.net/expression-language), which seems to do the trick.

**Comment by peeveen** [comment]
I had another play with this, adding in some `Nullable` support.

**Comment by abbasc52** [comment]
Hi @peeveen, I really appreciate the time and effort you put into this, but this is a solution only works for a corner case with number. Solving this problem in a generic manner for all edge case scenarios (beyond numbers) will open up gates for many more intricacy (This kind of utils might become a library on its own)

We can document this as a known issue as we already have multiple workarounds for this corner case : -
1. Use a strongly typed object to avoid this fuzzy conversion
2. Create your own variant of `CreateAbstractType` and use it before passing to RulesEngine.
3. Doing some transformations to ensure you data is consistent

We could use your efforts as a sample project on how to create custom abstract type converter. It will allow users to choose which route is more suitable for them and will prevent us from making any assumptions.

I would love to hear your thoughts on this.

**Comment by peeveen** [comment]
Oh, I absolutely acknowledge that this only really improves the "minimum service level" of **value type** handling. That was the entire scope of my objective.

Your suggested option 2 is probably the only one that could apply to my use case, as the data is purely dynamic. Converting dynamic lists into "known type" lists (using a copy of the `Utils` code from my PR) before passing them to the rules engine might be an option. I'll carry on using my fork of the engine code until I give that a try.

Thanks.

**Comment by abbasc52** [comment]
@peeveen RulesEngine also supports JObject for input types.
It can cover your scenario but might need some explicit casting in expression in some cases.
please refer https://github.com/microsoft/RulesEngine/issues/447
