### ISSUE TITLE
Performance issue when first time execute the rule validation

### ISSUE THREAD

**Issue by tangzhengyue** [microsoft/RulesEngine#439]
I have integrated the RulesEngine in one of my projects. Each call will new a RulesEngine and a Workflow to do the rule validation.
However, I found the first rule execution always have lower performance (about 200 ~ 300 milliseconds) and the following executions comes to normal (10 ~ 30 milliseconds). 
Since each execution is executed by new RulesEngine, I don't understand why the first execution always have lower performance? Any idea how can I improve it? Thanks.

**Comment by abbasc52** [comment]
@tangzhengyue , on first execution compilation of rule takes place which is then cached for then input. 
In case you change the input schema, or update workflow, it recompiles the rule.
In most of the other cases, the rules are available as compiled code, so it performs faster.

Can you share how many and how you have configured the rules? That will help us evaluate your performance concerns.
In the benchmark project, with simple test, it was taking ~6 microsec for execution (excluding first).

**Comment by abbasc52** [comment]
Closing this isssue due to inactivity
