### ISSUE TITLE
Nested property methods not found when inheriting from List<T>

### ISSUE THREAD

**Issue by duyn9uyen** [microsoft/RulesEngine#442]
This is strange but I noticed that calling nested properties work, but not nested methods.

```
// this works in the json rule
"expression": "input1.PropertyClass.MyProperty"

//this doesn't
"expression": "input1.PropertyClass.MyMethod('some string')"
```

This is the exception when trying to invoke nested methods:

> "Exception while parsing expression input1.PropertyClass.MyMethod(\"hello\") - No applicable aggregate method 'MyMethod(String)' exists"

How can I invoke nested methods from an expression?

**Comment by abbasc52** [comment]
Hi @duyn9uyen  can you share  how you are generating and passing input to RulesEngine?

**Comment by duyn9uyen** [comment]
I just pass in a class object into ExecuteAllRulesAsync();
```
var myCustomObject = new MyCustomObject();
var ruleResults = await engine.ExecuteAllRulesAsync("myworkflow-name", myCustomObject).ConfigureAwait(false);
```

The class is simple:
```
 public class MyCustomObject
 {
	public MySubClass PropertyClass { get; }
 }
 
 public class MySubClass
 {
	public bool MyMethod(string value)
	{
		if(value == "hello")
			return true;
	}
 }
```

**Comment by duyn9uyen** [comment]
I was hoping that someone can at least confirm whether this should work or not. I can't find a similar example of this. I only see root properties and methods being called by RE in your documentation.

**Comment by abbasc52** [comment]
It is supported and it seems to be working. Please refer this example - https://dotnetfiddle.net/TaAXmd

**Comment by abbasc52** [comment]
@duyn9uyen there are some corner case scenarios where it might not work. If you encounter such issue, you might want to register it in CustomTypes in ReSettings 
```c#
	var resettings = new ReSettings{
				  CustomTypes = new Type[]{typeof(MySubClass)}
			};


			var re = new RulesEngine.RulesEngine(new []{workflow},resettings);
```

**Comment by duyn9uyen** [comment]
> It is supported and it seems to be working. Please refer this example - https://dotnetfiddle.net/TaAXmd

Thank you for this example.  Looks like if a class inherits from a `List<T>`, the expression breaks. Adding this custom type to the ReSettings didn't work. Here is an example of that. https://dotnetfiddle.net/pFKWU6.

**Comment by everettcomstock** [comment]
@abbasc52 , we're happy to do some investigation to see if it's possible to support this scenario. Any chance you can give us some pointers as to where to start in the code?

**Comment by abbasc52** [comment]
> @abbasc52 , we're happy to do some investigation to see if it's possible to support this scenario. Any chance you can give us some pointers as to where to start in the code?

Hi @everettcomstock, this seems to be an issue with dynamic.linq.core library which is primarily used for expression parsing. I had dug deep into their implementation, and it seems they handle `IEnumerable` related classes separately.

I still need to go through the example to see if there is any workaround and if there is a scope to support it. Although this is a corner case, I will let you know if there is an opportunity to support it.

**Comment by abbasc52** [comment]
@everettcomstock As I mentioned earlier, this bug comes from source library. If you want to look at implementation here are the code reference.
https://github.com/zzzprojects/System.Linq.Dynamic.Core/blob/f4bfa99295d23fb32812055757aca8b0cd0efa30/src/System.Linq.Dynamic.Core/Parser/ExpressionParser.cs#L1651-L1664

Basically, if a class extends `IEnumerable` they do the method check only on a subset of predefined values

@duyn9uyen I would like to further understand your requirement to extend a List class.
If you need a workaround a static utils method can do the trick
Please refer - https://dotnetfiddle.net/f7Ccx0

**Comment by duyn9uyen** [comment]
> @duyn9uyen I would like to further understand your requirement to extend a List class. If you need a workaround a static utils method can do the trick Please refer - https://dotnetfiddle.net/f7Ccx0

Yea we can use a util class as a workaround instead. Thanks for looking it.
