### ISSUE TITLE
Arrays in dynamic objects with different properties

### ISSUE THREAD

**Issue by macxdev** [microsoft/RulesEngine#447]
Thank you for this excellent and simple rules engine. Implementing this with a complex JSON where the JSON can be highly dynamic for a combination of filters and found the following:
This occurs If the JSON has an array and each object in the array is slightly different. 
Input parameter is (ExpandoObject, showing JSON for it)
```
{
	"lines": [{
			"property1": "value",
			"property2": "value"
		},
		{
			"property1": "value",
			"property2": "value",
			"property3": "new value"
		}
	]
}
```
The input parameter passed to the rule for execution has the list of 'lines' in which for index 1 property3 does not exists
i.e. 
`_input1.lines[1].property3 does not exists` 

If the input parameter (ExpandoObject, showing JSON for it)
```
{
	"lines": [{
			"property1": "value",
			"property2": "value",
			"property3": "value"
		},
		{
			"property1": "value",
			"property2": "value"
		}
	]
}
```
The input parameter passed to the rule for execution has the list of 'lines' in which for index 0 property3 exists, and is null for index 1
i.e.
```
_input1.lines[0].property3="value";
_input1.lines[1].property3=null;
```
If the input parameter (ExpandoObject, showing JSON for it)
```
{
	"lines": [{
			"property1": "value",
			"property2": "value",
			"property3": "value"
		},
		{
			"property1": "value",
			"property2": "value",
			"property3": "new value"
		}
	]
}
```
The input parameter passed to the rule for execution has the list of 'lines' in which for index 0 property3 exists, and  for index 1 has the correct value
i.e.
```
_input1.lines[0].property3="value";
_input1.lines[1].property3="new value";
```

**Comment by abbasc52** [comment]
Hi @macxdev, Thanks for raising this issue, It helped me discover a universal solution for such scenarios
For complex json scenarios, you can pass `JObject` instead of ExpandoObject. 
It supports all access scenario and equality checks.
i.e
```
_input1.lines[0].property3="value";
_input1.lines[1].property3="new value";
```
works out of the box;

For advance access (calling a method, performing operations( +,-, etc)), you might need to cast the object.
Casting syntax in rulesEngine is different from regular c#
``` explicit cast to a type
typename(<expression>)

e.g. string(input1.lines[0].property3)

``` As based conversion (value as string in regular c#
As(<expression>,typename)

e.g. As(input1.lines[0].property3,string)
```

It will take me sometime to document, usage of JObject over ExpandoObject. You can try it out and see if it  



```

**Comment by macxdev** [comment]
Thanks @abbasc52 for the response, I greatly appreciate it. I will give it a go tomorrow and report if I find anything. For the conversions, thank you and also thank you for adding the ability to add helper classes, the one I wrote I think should be able to handle it.

**Comment by macxdev** [comment]
@abbasc52  thank you, confirming this is working well i.e. using JObject. The rules are also simpler. Thank you. As I have a fair few rules to check this on if I find any other issue will open a new one. 
Thank you again for the response and the solution.
