### ISSUE TITLE
Can preview nuget package feed be setup?

### ISSUE THREAD

**Issue by kdcllc** [microsoft/RulesEngine#45]
I noticed that there are many changes in the dev branch but no preview, beta package. Can feedz.io feed be setup for the dev branch?

Thanks

**Comment by abbasc52** [comment]
Hi @kdcllc 
We do intend to set up preview feed. Currently the changes in dev are breaking changes, so we dont want to setup migration for users for every change in preview. That said we will be soon releasing a preview feed via [github packages](https://github.com/features/packages)

**Comment by abbasc52** [comment]
@kdcllc  we have set up preview feed under github packages - https://github.com/microsoft/RulesEngine/packages/449001
I hope that works for you 😄

**Comment by kdcllc** [comment]
@abbasc52 what branch does the build utilizes for the preview packages?

**Comment by abbasc52** [comment]
@kdcllc it is based on develop branch
