### ISSUE TITLE
Unable to exit once a particular rule is matched

### ISSUE THREAD

**Issue by subrata1106** [microsoft/RulesEngine#453]
Is there an option to indicate existing the process once a particular rule is matched

**Comment by subrata1106** [comment]
not sure whether this is the right forum or not - but if i have some question on implementation = can someone help me out

**Comment by abbasc52** [comment]
@subrata1106 do you mean you want to end the execution once a rule is matched?

**Comment by subrata1106** [comment]
@abbasc52 Yes

**Comment by abbasc52** [comment]
@subrata1106 by default, RulesEngine evaluates all rules. If you need the process to exit on match, you can enable it by passing the following settings-
```
 var reSettings = new ReSettings { NestedRuleExecutionMode = NestedRuleExecutionMode.Performance };
var rulesEngine = new RulesEngine(workflow, reSettings: reSettings);
``

**Comment by subrata1106** [comment]
thanks a lot @abbasc52
