### ISSUE TITLE
Why does the expression of the parent rule become invalid when the parent rule has child rules?

### ISSUE THREAD

**Issue by jing1345061** [microsoft/RulesEngine#467]
Parent rule and child rule. When the parent rule has "Expression", the expression of the parent rule should be run first. When the parent rule is "false", all child rules will not be run. Why does the expression of the parent rule become invalid when the parent rule has child rules? What can I do to achieve this result?
The result I want in the illustration is that the rule is false
![image](https://user-images.githubusercontent.com/24875979/221062027-cd5d734b-4381-4c7f-83e3-389d9081051f.png)

**Comment by abbasc52** [comment]
@jing1345061 RulesEngine only allows leaf rules to have expression. As such passing expression to parent rule is invalid and is ignored.

**Comment by ying234** [comment]
If RulesEngine can have an options to also allow parent expression, that will be able to support nest if else and to make the expressions much simpler in some situations.
