### ISSUE TITLE
Microsoft Json Rule Engine Custom Error Message

### ISSUE THREAD

**Issue by Wolf1329** [microsoft/RulesEngine#468]
I am using the following library for json base rule engine. https://github.com/microsoft/RulesEngine

I want to concatenate property value into error message. I have a list of collection and I want to concatenate what item in the list satisfy the expression criteria.

```
{
        "RuleName": "CheckforVTPumpSelectionErrors121-03",
        "ErrorMessage": "WARNING: 121 - VT PUMP Manual Pick Required for {0} HP {1} pump!",
         "Expression": "ProductFamily.PumpConfigurations.Any(r => r.PumpDescription == \"Water Feature\" || r.PumpDescription == \"Transfer\") && Flag1 == false"
}
```
I want to replace {0} with horse power value.

My DTO:
```
public class ProductFamily
    {
        public int SCCR = 30;
        public List<PumpConfiguration> PumpConfigurations { get; set; }
    }

 public class PumpConfiguration
    {
        public PumpConfiguration()
        {
        }
        public string PumpDescription { get; internal set; }
        public int HP { get; internal set; }
    }

```
[From stackoverflow](https://stackoverflow.com/questions/68267710/microsoft-json-rule-engine-custom-error-message)

**Comment by pramireddy** [comment]
I think  current RulesEngine  have this implementation as Tested at https://github.com/microsoft/RulesEngine/blob/main/test/RulesEngine.UnitTest/BusinessRuleEngineTest.cs ::

Line Number : 325
Test Method:
 public async Task RulesEngine_Execute_Rule_For_Nested_Rule_Params_Returns_Success(string ruleFileName)

**Comment by abbasc52** [comment]
Parsing value from list of expression in error message is not supported. you could loop your collection and call rulesEngine for each value.
