### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by asulwer** [microsoft/RulesEngine#47]
it seems like the examples section is lacking.  the wiki seems to be thin too.  what would it take to see some examples?  specifically how others are using this system?

**Comment by asulwer** [comment]
here is an example of how i am attempting to use this.

nuget package DynamicExpresso.Core is necessary

`string sRemoveFoil = @"{
                'WorkflowName': 'RemoveFoil',
                'Rules': [{
                    'RuleName': 'NameContains',
                    'ErrorMessage': 'rule failed',
                    'ErrorType': 'Error',
                    'RuleExpressionType': 'LambdaExpression',
                    'SuccessEvent': 'card.Name = card.Name.Replace(""Foil"", string.Empty).TrimEnd()',
                    'Expression': 'input1.Name.Contains(""Foil"") == true'
                },
                {
                    'RuleName': 'NameContains',
                    'ErrorMessage': 'rule failed',
                    'ErrorType': 'Error',
                    'RuleExpressionType': 'LambdaExpression',
                    'SuccessEvent': 'card.Name = card.Name.Replace(""("", string.Empty).TrimEnd()',
                    'Expression': 'input1.Name.Contains(""("") == true'
                },
                {
                    'RuleName': 'NameContains',
                    'ErrorMessage': 'rule failed',
                    'ErrorType': 'Error',
                    'RuleExpressionType': 'LambdaExpression',
                    'SuccessEvent': 'card.Name = card.Name.Replace("")"", string.Empty).TrimEnd()',
                    'Expression': 'input1.Name.Contains("")"") == true'
                },
                {
                    'RuleName': 'NameContains',
                    'ErrorMessage': 'rule failed',
                    'ErrorType': 'Error',
                    'RuleExpressionType': 'LambdaExpression',
                    'SuccessEvent': 'card.Name = card.Name.Replace("" -"", string.Empty).TrimEnd()',
                    'Expression': 'input1.Name.Contains("" -"") == true'
                }]
            }";

            List<Card> cards = new List<Card>
            {
                new Card
                {
                    Name = "Test1 - Foil"
                },
                new Card
                {
                    Name = "Test2 (Foil)"
                },
                new Card
                {
                    Name = "Test3 - (Foil)"
                },
                new Card
                {
                    Name = "Test4 (Oversized)"
                },
                new Card
                {
                    Name = "Test5 - (Oversized)"
                }
            };

            WorkflowRules wrRemoveFoil = JsonConvert.DeserializeObject<WorkflowRules>(sRemoveFoil);

            var bre = new RulesEngine.RulesEngine(null);

            bre.AddWorkflow(new[] { wrRemoveFoil });

            foreach (Card c in cards)
            {
                List<RuleResultTree> resultList = bre.ExecuteRule("RemoveFoil", c);

                foreach (var result in resultList)
                {
                    if (!result.IsSuccess)
                        continue;

                    var target = new Interpreter();
                    target.Eval(result.Rule.SuccessEvent, new Parameter("card", typeof(Card), result.Input));
                }
            }`

**Comment by abbasc52** [comment]
Hi @asulwer , It seems github has introduced discussions which seem to be more appropriate for such discussions.
Request you to move the sample code to [RulesEngine usecase examples](https://github.com/microsoft/RulesEngine/discussions/86) and close this issue
