### ISSUE TITLE
Exception while parsing expression; Expression of type 'Boolean' expected

### ISSUE THREAD

**Issue by Sangeetha-Murugesan** [microsoft/RulesEngine#482]
Hi,

I want to execute the following rule, in the Expression instead of returning a boolean, i want to return some object say string. But when I execute the rule, I am getting this error : "_Exception while parsing expression `input1.country == \"india\" ? \"india\" : \"other country\" ` - Expression of type 'Boolean' expected_" . Do I need to add any extra condition to achieve this?

**Rule :** 
  [
    {
      "WorkflowName": "Discount",
      "Rules": [
        {
          "RuleName": "GiveDiscount10",
          "SuccessEvent": "10",
          "ErrorMessage": "One or more adjust rules failed.",
          "ErrorType": "Error",
          "RuleExpressionType": "LambdaExpression",
          "Expression": _"input1.country == \"india\" ? \"india\" : \"other country\" "_
        }
      ]
    }
  ]

**Input** :  {"name": "hello","email": "abcy@xyz.com","creditHistory": "good","country": "canada","loyaltyFactor": 3,"totalPurchasesToDate": 10000};

**Comment by abbasc52** [comment]
Rule expression only supports boolean logic, If you want output , please use output actions https://microsoft.github.io/RulesEngine/#outputexpression
