### ISSUE TITLE
Struggling with dynamic link in CustomTypes - .Any() / Char.IsLetterOrDigit

### ISSUE THREAD

**Issue by dhagan-va** [microsoft/RulesEngine#483]
Hi Folks, Thank you for a great RulesEngine!

I am having some success and some struggle with authoring expressions  --

 "Expression": "\"dougy\".All(Char.IsLetterOrDigit)"

https://dotnetfiddle.net/737myq

Exception while parsing expression `"dougy".Any(Char.IsLetterOrDigit)` - No property or field 'IsLetterOrDigit' exists in type 'Char'

TestChar-1 :
IsSuccess- False
 
 Exception while parsing expression `"dougy".All(c=>Char.IsLetterOrDigit(c) || c=='_')` - No applicable method 'IsLetterOrDigit' exists in type 'Char'

TestAll :
IsSuccess- False
 
 Exception while parsing expression `"dougy".All()` - No applicable method 'All' exists in type 'String'

**Comment by bmasotta-lcg** [comment]
The expression context is not the same as writing regular .NET code, please refer to https://dynamic-linq.net/expression-language
that's the library the RulesEngine is using for parsin the expressions (see "Accessible Types" section)

**Comment by dhagan-va** [comment]
Thank you for the kind reply - can you suggest a way I might accomplish -

`new String[] { \"first\", \"second\", \"third\" }.Any((c) => c == \"first\")"`

**Comment by dhagan-va** [comment]
It's in wiki!  Thanks!
`
"Expression": "Utils.CheckContains(input1.country, \"india,usa,canada,France\") == true"`
