### ISSUE TITLE
How to write Expressions for an Array in input source?

### ISSUE THREAD

**Issue by SaviChinnadurai** [microsoft/RulesEngine#5]
Hi,

I have a requirement to execute a condition on an array in input source and return true for all or any passed.
Example:
Input Object:
{
    "company":"ABC Limited",
    "branches": [
               { "city": "London", "Region":"Europe" },
               { "city": "Paris", "Region":"Europe" },
               { "city": "Germany", "Region":"Europe" },
     ]
}

How do I write the LamdaExpression for condition like below:

   "input.branches.All(b => b == 'Europe')"

**Comment by dishantmunjal** [comment]
Hi @SaviChinnadurai 
I don't think we have anything right out of the box for such scenario but there is a provision to add custom functions as expressions. 
Please have a look at [ReSettings](https://github.com/microsoft/RulesEngine/wiki/Getting-Started#resettings) in the [wiki](https://github.com/microsoft/RulesEngine/wiki) and see if that helps.
Let us know if any help is required in handling that.

**Comment by dishantmunjal** [comment]
Closing this issue as OP has not responded yet. @SaviChinnadurai feel free to reopen it if you are still facing this issue
