### ISSUE TITLE
Custom method question

### ISSUE THREAD

**Issue by bjsapir** [microsoft/RulesEngine#50]
I have a simple custom class & method: Utils.Equals(string a, string b)
and calling it in an "Expression": "Utils.Equals(input1.Thing1, "\something\") == true"

and get an exception from the rules engine. I have tried adding (string)input1.Thing1 to the expression
but it doesn't work. I'm not sure how to convert input1.Thing1 into a string. I believe the input.Thing1
is a dynamic object so the rules engine can't match it to a string type?
I'm just trying to understand how the custom methods will work and need a working example.

I have also seen others trying to pass an Array of objects as an argument so one can
check if it contains an item. Can an example be provided?

**Comment by abbasc52** [comment]
Hi @bjsapir 

> I have a simple custom class & method: Utils.Equals(string a, string b)
> and calling it in an "Expression": "Utils.Equals(input1.Thing1, "\something") == true"
> 
> and get an exception from the rules engine. I have tried adding (string)input1.Thing1 to the expression
> but it doesn't work. I'm not sure how to convert input1.Thing1 into a string

For type conversion, in your case the syntax will be  `Utils.Equals(string(input1.Thing1), "\something") == true"`
For extensive details on expression grammer, you can refer - https://dynamic-linq.net/expression-language
It is mostly similar to c# language syntax with few minor differences


>  I believe the input.Thing1
> is a dynamic object so the rules engine can't match it to a string type?

RulesEngine only uses dynamic object if you don't pass a strongly typed object. If you pass a typed object, it will take the type that you passed.


> I have also seen others trying to pass an Array of objects as an argument so one can
> check if it contains an item. Can an example be provided?

Can you provide more details on this?
You can refer [DemoApp](https://github.com/microsoft/RulesEngine/tree/master/demo/DemoApp) the BasicDemo covers multiple inputs passed to RuleEngine and NestedInputDemo covers how highly nested objects can be used along with accessing list properties

**Comment by bjsapir** [comment]
I had a mistake in my json payload
causing my issues. The exception was confusing but finally figured it out.
The problem has been resolved.

For the arrays question I tested a json array of objects where my rule
calls

Utils.CheckArrayContains(input1.ArrayOfObjects, \”key\”, \”value\”)

and the Utils class defined as
CheckArrayOfObjects(IEnumerable theArray, string key, string value)

Once I defined the method that way I was
able to proceed in the logic.

Thanks!

**Comment by abbasc52** [comment]
@bjsapir can you describe the exception you were getting? so that we can provide a more user friendly message if possible

**Comment by bjsapir** [comment]
I’m sorry I did not save the error or
the input and cannot recreate it.
If I do run across it again I will post it for you.

**Comment by abbasc52** [comment]
@bjsapir i am closing this issue since you were able to get it running.
