### ISSUE TITLE
For loop in rule engine

### ISSUE THREAD

**Issue by akshay2988** [microsoft/RulesEngine#506]
I have scenario in which I need to traverse through multiple records in excel sheet against one condition. So is it possible to use for loop any how in MS rule engine rule expression ? If no, what could be possible alternate solution?

**Comment by abbasc52** [comment]
@akshay2988 , you could try using Linq operation in condition.
RulesEngine also offers you to inject custom class and add complex logic in it. Please refer - https://github.com/microsoft/RulesEngine/wiki/Getting-Started#resettings
