### ISSUE TITLE
Ignore case when comparing string values

### ISSUE THREAD

**Issue by gvsireesh** [microsoft/RulesEngine#51]
Hi when I tested the demo the string values are not ignore case comparision. I'm using "RuleExpressionType": "LambdaExpression".
for example 
if I have an expression 
"Expression": "input1.country== \"india\""
input1.country.Contains(\"ind\")
pass the country value india the result will be true. however if change the case to INDIA or India the result is giving false.
Is there a way I can say to rule engine to use ignore case when comparing strings

**Comment by David-Moreira** [comment]
Hello,
You can just tell the expression to be case insensitive when comparing them, like you would when comparing strings in .NET.
Something like this:
"Expression": "input1.country.Contains(\"india\",StringComparison.OrdinalIgnoreCase) == true"

**Comment by abbasc52** [comment]
@gvsireesh i am closing this issue since @David-Moreira has provided the correct answer. Feel free to reopen this if you are still facing this issue
