### ISSUE TITLE
Issue with nuget package, same code work in basedemo project but not when create new project and add nuget package

### ISSUE THREAD

**Issue by gvsireesh** [microsoft/RulesEngine#52]
I wrote custom code create workflow rules and rule definitions. The code works perfectly fine when I add it to the base demo project that is part of RulesEngine repo howeve the same code throws exceptions if I create a new console and add the latest nuget package and run.

Exception I get is 

Unable to cast object of type 'System.Linq.Expressions.InstanceMethodCallExpression1' to type 'System.Linq.Expressions.BinaryExpression'.

 public void Run()
        {
            List<Rule> ruleDefintions = new List<Rule>();
            ruleDefintions.Add(new Rule
            {
                RuleName = "test",
                RuleExpressionType = RuleExpressionType.LambdaExpression,
                Expression = "input1.GRADE.Contains(\"720\")"
            });
            var workflowRules = new List<WorkflowRules>
            {
                new WorkflowRules
                {
                    WorkflowName = "test"
                }
            };
            workflowRules[0].Rules = ruleDefintions;
            var item = new ExpandoObject();
            AddProperty(item, "GRADE", "720-1");
            var inputs1 = new[]
            {
                item
            };
            var customUtils = new ReSettings { CustomTypes = new[] { typeof(ExpressionUtils) } };
            var bre = new RulesEngine.RulesEngine(workflowRules.ToArray(), null, customUtils);

            List<RuleResultTree> resultList = bre.ExecuteRule("test", inputs1);
            Console.WriteLine(resultList.Count);
        }

        /// <summary>
        /// Adds properties to expando object.
        /// </summary>
        /// <param name="parameterInput"> The parameter input.</param>
        /// <param name="propertyName">The property name.</param>
        /// <param name="propertyValue">The property value.</param>
        private static void AddProperty(ExpandoObject parameterInput, string propertyName, object propertyValue)
        {
            // ExpandoObject supports IDictionary so we can extend it like this
            var expandoDict = parameterInput as IDictionary<string, object>;
            if (expandoDict.ContainsKey(propertyName))
            {
                expandoDict[propertyName] = propertyValue;
            }
            else
            {
                expandoDict.Add(propertyName, propertyValue);
            }
        }

**Comment by abbasc52** [comment]
@gvsireesh Please provide the details of branch and nuget version that you are referring to?

**Comment by David-Moreira** [comment]
Hello.
I have found the same issue. This happens because the RulesEngine expects a BinaryExpression. 
Since your expression
"input1.GRADE.Contains("720")" is compiled into a MethodCallExpression, it throws an exception.
 Unable to cast object of type 'System.Linq.Expressions.InstanceMethodCallExpression1' to type 'System.Linq.Expressions.BinaryExpression'.

To fix this you can just rewrite your expression into: "input1.GRADE.Contains("720") == true" which will compile into a BinaryExpression which is expected by the RulesEngine.

@abbasc52 I have also made a Pull Request with this fix.

**Comment by abbasc52** [comment]
this has been fixed and releases as a part of v2.1.2. Thanks @David-Moreira  for your contribution.
