### ISSUE TITLE
Expression of type 'Boolean' expected

### ISSUE THREAD

**Issue by MayueCif** [microsoft/RulesEngine#522]
I'm trying to determine if it's a type, prompting
Exception while parsing expression `Payload is string` - Expression of type 'Boolean' expected

**Comment by robin-o** [comment]
The expression isn't C#, its using [dynamic expressions](https://dynamic-linq.net/expression-language#is-and-as-examples). Try `Is(Payload, \"string\")`.

**Comment by abbasc52** [comment]
@MayueCif  please try the solution suggested by @robin-o
