### ISSUE TITLE
Issue with Object Type Changing

### ISSUE THREAD

**Issue by larsontim12** [microsoft/RulesEngine#54]
I have a object example of dynamic object called Orders and a list of Products with ProductID and Gross and Net.  I have the Gross and the Net set set as Double and add the different products to the the order.  If the first product has the Gross or the Net as 999 instead of 999.99 it is trying to make the entire List of products be an Int64 instead of Double and the rest of the validation for the other products in the list are double it fails saying:

System.ArgumentException: 'Object of type 'System.Double' cannot be converted to type 'System.Int64'.'

Any ideas how I can force the values to stay being double?

Thanks,
Tim

**Comment by livlif2dfullest** [comment]
How did you resolve this?  I am experiencing the same issue.
