### ISSUE TITLE
Comparisons with nullable types

### ISSUE THREAD

**Issue by celi** [microsoft/RulesEngine#558]
Hi, code like this

```
        decimal? d1 = null;
        var result = d1 < 20;
```

run in c# return **false**, but same comparison run in RulesEngine return **true**, why?

**Comment by abbasc52** [comment]
@celi i can maybe add option to disable fast compile if needed, it will be a tradeoff between performance vs accuracy
Would that work for you?

**Comment by celi** [comment]
@abbasc52 Yes, please.
I didn't test decrease of performance without FastExpressionCompiler yet, but I plan to do that. It will be easier with this switch.

**Comment by abbasc52** [comment]
@celi  can you share complete sample code to reproduce this issue?

**Comment by celi** [comment]
@abbasc52 https://github.com/celi/MsRulesEngineCompareWithNullBug

just run `dotnet run` in project folder
