### ISSUE TITLE
Support for CheckListContains and CheckObjectContains in ExpressionUtils

### ISSUE THREAD

**Issue by srikanthneostar** [microsoft/RulesEngine#6]
Hi Sir,
          My name is srikanth. I have been following this project and i think it is great work. Thanks for coming up with such concept. I had few things to ask can you please help answer them. 
In your class ExpressionUtils can you please add support to these two methods. 

 public static bool CheckListContains(IEnumerable<object> list, string value, string prop = null)
        {
            if (list == null || list.Count() == 0)
                return false;
            if (prop == null)
                return list.Contains(value);
            else
            {
                foreach (object singleObj in list)
                {
                    if (singleObj != null)
                    {
                        PropertyInfo property = singleObj.GetType().GetProperty(prop);
                        if (property != null)
                        {
                            var _val = property.GetValue(singleObj);
                            if (_val.ToString().Equals(value))
                            {
                                return true;
                            }
                        }
                    }
                }
                return false;

            }
        }

        public static bool CheckObjectContains(object obj, string value, string prop = null)
        {
            return CheckListContains(new List<object> { obj }, value, prop);
        }

As well Iam currently building an analytics product . Would like use your project for business work rules. Can i pick up the code drop and make it part of the project or should i be only going through nuget. I would also be happy to contribute and help add some features support as part of this curve. Please let me know.

**Comment by abbasc52** [comment]
Hi @srikanthneostar, i am glad that you like this project. 
Regarding your query, You can create your own static Utils class and register it to be picked up by the expressions
```
var reSettings = new ReSettings{
	CustomTypes = new Type[] {MyCustomClass}
}

var bre = new BusinessRuleEngine(workflows, logger, reSettings)
```

With this you can use it in expressions as 
`MyCustomClass.CheckObjectContains(obj, "value", prop) == true`

Let me know if this solves your issue 😄

**Comment by srikanthneostar** [comment]
Thanks . this is great I can now go through nu get. Can you also please confirm the commercial use of the package.

**Comment by abbasc52** [comment]
This library is under MIT license, so feel free to use it for commercial use.

**Comment by srikanthneostar** [comment]
Hey thanks a lot, this will help us a lot. Thanks again great work
