### ISSUE TITLE
Support Json or xml as input?

### ISSUE THREAD

**Issue by maikebing** [microsoft/RulesEngine#64]
Looks like it's not supported at the moment?

**Comment by abbasc52** [comment]
@maikebing Can you provide more details on this?

**Comment by maikebing** [comment]
My device sends data through mqtt, the data format is jason format, I want to process the data through this project.

**Comment by maikebing** [comment]
e.g 
`{ “age”:90 }`

**Comment by abbasc52** [comment]
RulesEngine supports dynamic objects as input.
If you convert json to dynamic object, it should work with rulesengine.
```c#
var expConverter = new ExpandoObjectConverter();
dynamic input = JsonConvert.DeserializeObject<ExpandoObject>(jsonObject, expConverter);

var results = rulesEngine.ExecuteRule("myworkflow",input);
```
Let me know if this works

**Comment by maikebing** [comment]
Thank you! Next I'll try to do that.

**Comment by abbasc52** [comment]
@maikebing i am closing this issue. If you still face this issue, feel free to reopen it
