### ISSUE TITLE
First call of Utils.GetTypedObject is very slow

### ISSUE THREAD

**Issue by KoalaBear84** [microsoft/RulesEngine#65]
We have an entity with 182 fields, which can contain different data types in the fields.

Translate the entity to a `IDictionary<string, object>`, run it through `Utils.GetTypedObject` which is slow the first time.

```csharp
static IDictionary<string, object> GetEntityValues(Entity entity)
{
	ExpandoObject entityExpandoObject = new ExpandoObject();
	IDictionary<string, object> entityValues = entityExpandoObject;

	foreach (Field field in entity.Fields)
	{
		entityValues.Add(field.FieldType.Id, field.Data);
	}

	return entityValues;
}

// 10 items
List<Entity> items = GetItems();

// Doesn't make any difference, so it's not a particular item
//items.Reverse();

// Just in case for testing
await Task.Delay(TimeSpan.FromSeconds(5));

foreach (Entity item in items)
{
	IDictionary<string, object> entityValues = GetEntityValues(item);
	Stopwatch stopwatch = Stopwatch.StartNew();
	object itemEntityTyped = Utils.GetTypedObject(entityValues);
	Console.WriteLine($"GetTypedObject3 [{item.Id}]: {stopwatch.ElapsedMilliseconds}ms");
}
```

Results:

```
GetTypedObject: 824ms
GetTypedObject: 157ms
GetTypedObject: 149ms
GetTypedObject: 144ms
GetTypedObject: 134ms
GetTypedObject: 145ms
GetTypedObject: 186ms
GetTypedObject: 158ms
GetTypedObject: 191ms
GetTypedObject: 133ms
```

The first time it always is around 4 times slower. Is Utils.GetTypedObject still needed? Is there any way to let it use a Dictionary instead, or is there some other way we can improve the performance?

I know my work laptop isn't that fast, Intel Core i5-6200U, but it should be faster to convert 182 fields.

Executing the rules itself always is fast, at least no problems there. But, we currently only use like `entity.Field == true`.

I've created a separate reproduce solution for it. Which strangely is faster than the above stats.

[ConsoleApp_20201028_1431_GetTypedObjectReproduce.zip](https://github.com/microsoft/RulesEngine/files/5452293/ConsoleApp_20201028_1431_GetTypedObjectReproduce.zip)

```
Started!
Loading values from file...
Loaded values from file
Wait 5 seconds...
Run 0, GetTypedObject: 66ms
Run 1, GetTypedObject: 0ms
Run 2, GetTypedObject: 0ms
Run 3, GetTypedObject: 0ms
Run 4, GetTypedObject: 0ms
Run 5, GetTypedObject: 0ms
Run 6, GetTypedObject: 0ms
Run 7, GetTypedObject: 0ms
Run 8, GetTypedObject: 0ms
Run 9, GetTypedObject: 0ms
Finished!
```

**Comment by abbasc52** [comment]
@KoalaBear84 GetTypedObject only converts an object if the type is not present(if type of object is expandobject). In the sample that you shared since you convert it to dictionary<string,object> it does not run any type conversion logic and hence is fast.

As for dictionary support, it should support basic use case as you mentioned in v2.1.4+. I will try adding some test case with dictionary<string,object>. Meanwhile you can consider your dictionary<string,object> as a dynamic object and check if it improves performance

**Comment by KoalaBear84** [comment]
Thanks for your reply. I've removed the extra call. Will be tested tomorrow and I'll update this ticket accordingly.

**Comment by KoalaBear84** [comment]
It's tested and the rules work. Strangely there are still some big fluctuations in the ExecuteRule. But that is strange, looks like the issues are a problem from the system, not the Rules Engine. Thanks!
