### ISSUE TITLE
Strange performance fluctuations

### ISSUE THREAD

**Issue by KoalaBear84** [microsoft/RulesEngine#67]
After #65 was closed and have removed `Utils.GetTypedObject` we still have large performance fluctuations.

**Code:**
```csharp
IDictionary<string, object> entityValues = GetEntityValues(entity);
Stopwatch stopwatch = Stopwatch.StartNew();
List<RuleResultTree> resultList = rulesEngine.ExecuteRule(WorkflowCode, new RuleParameter("entity", entityValues));
Log(LogLevel.Information, $"[{entity.Id}] ExecuteRule: {stopwatch.ElapsedMilliseconds}ms");
```

We could have multiple rules for a single entity to check if it validates. Currently only 2 rules containing only expressions like `entity.Field == true`.

**Log:**
```
Information [37840] ExecuteRule: 1ms
Information [37840] ExecuteRule: 1ms
Information [37840] ExecuteRule: 206ms
Information [37840] ExecuteRule: 1970ms
Information [37840] ExecuteRule: 1938ms
Information [37840] ExecuteRule: 1896ms
Information [37840] ExecuteRule: 1ms
Information [37840] ExecuteRule: 1ms
Information [37840] ExecuteRule: 1ms
Information [37840] ExecuteRule: 1ms
Information [37840] ExecuteRule: 1910ms
Information [37840] ExecuteRule: 1ms
```

This is a very bad run, many times 1ms, but also 4 times almost 2 seconds. Any idea what could be fluctuating?

I couldn't find a memory leak when running it a million times.

**Comment by abbasc52** [comment]
@KoalaBear84 it is difficult to comment but it seems we need to come up with some benchmarking numbers at our side. We will investigate on what possibly could cause such fluctuation

**Comment by KoalaBear84** [comment]
I've seen new performance improvements incoming, those focus on parsing/compiling of the rules, which of course is great!

On our side it's the executing of it, I've added a comment on the commit:
https://github.com/microsoft/RulesEngine/commit/51ccb7f99c3a24beda334337ee486d692f60c3aa

Maybe, when this is released, we could try the new version and recreate the RulesEngine every time, because parsing could be faster. But still won't solve a strange underlying issue. Memory leak over time? It's really strange.

**Comment by abbasc52** [comment]
@KoalaBear84 as per benchmark on the new perf improvement, it is 25% faster as is and upto 35% by disabling optional features. 
Regarding memory leak, there is a potential fix in preview version where we replaced concurrent dictionary with memoryCache which would clean up on its own over time. I am planning to release the new preview version with perf improvements in a week. Meanwhile I will check if any code can cause a memory leak.
We too use RulesEngine in production, I will try getting stats and see if i find any pattern.

**Comment by abbasc52** [comment]
@KoalaBear84  could you try using the v3.0.0-preview.2 and see if you still face the issue?

**Comment by KoalaBear84** [comment]
OK, thanks, will probably create a version today, if time is cooperating. And then we'll know very soon.

**Comment by KoalaBear84** [comment]
Damn.. I can't get it to work. Already added `Microsoft.Bcl.AsyncInterfaces.dll` and `FastExpressionCompiler.dll`, and already was using Microsoft.Extensions.*.dll in the release.

`Could not load file or assembly 'Microsoft.Extensions.Options, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

When I check the DLL, everything looks fine to me:

![image](https://user-images.githubusercontent.com/5886900/99556491-ddb53780-29c1-11eb-81ba-3b349fe1b739.png)

Any idea?

**Comment by abbasc52** [comment]
Which .net framework are you using?

**Comment by KoalaBear84** [comment]
Found it on the 'server' (Azure Service Fabric of SaaS supplier) using https://stackoverflow.com/a/951915/951001 and got 461814 which is:

_461814 - .NET Framework 4.7.2 (On all Windows operating systems other than Windows 10 April 2018 Update and Windows Server, version 1803)_

https://www.admin-enclave.com/en/articles/windows/370-find-out-which-net-framework-version-is-installed.html

So .NET Framework 4.7.2

This is the DLL's I'm supplying net to the package is:

![image](https://user-images.githubusercontent.com/5886900/99569613-21636d80-29d1-11eb-87b7-f3ced13fafa4.png)

**Comment by abbasc52** [comment]
This might be related to version update. Check your web.config for all Microsoft.Extension reference and update 3.1.0.0 to 3.1.6.0.

.Net framework has a very messy way of dealing with dependency

**Comment by KoalaBear84** [comment]
It does not have a web.config or app.config because it is loaded as an extension. Probably something like a LoadLibrary call or something.

I'll try to see if there is a way to have any guidance in all of this and will update this issue after that.

**Comment by KoalaBear84** [comment]
We found a way to 'fix' the issue by adding `/closed` to the ilmerge command, found on https://stackoverflow.com/a/2367264/951001

Will update this soon when it is published on production and we have the results.

**Comment by KoalaBear84** [comment]
We have the results. The processing time is still increasing the longer it runs.

So it must be some sort of memory related issue? But that was already a separate path that was being looked into if I'm right.

**Comment by rahul24** [comment]
Is this fixed?

**Comment by KoalaBear84** [comment]
We stopped using it for now because we have only 3 simple rules and hardcoded them.

We are too afraid to use it again 😬

The only thing we use it for is look if entity values match the expression. Like entity.field == "value". Maybe the RulesEngine is overkill for this?

**Comment by abbasc52** [comment]
@KoalaBear84 sorry to hear that. We also are unable to reproduce this, we have multiple internal systems who use it and yet no one has been able to reproduce this issue. 

I would like to know some details which might help us reproduce this :
- Does your input data model/fields change frequently?
- Do you only face it while using Dictionary<string,object> or are even able to reproduce it with dynamic object?
- Is RulesEngine used as a singleton or disposed and recreated during the lifecycle?

@rahul24 , as mentioned by @KoalaBear84 , we are unable to reproduce it and have very little details on what might be causing it. If you are facing similar issue, any additional detail might help.

**Comment by KoalaBear84** [comment]
*   Does your input data model/fields change frequently?

The definition of the input does not change that often. Most of the time it's an entity with 150 fields or so, but the entity type could change.

*   Do you only face it while using Dictionary\<string,object> or are even able to reproduce it with dynamic object?

Didn't try changing that, but could check that when there is time to look at it again.

*   Is RulesEngine used as a singleton or disposed and recreated during the lifecycle?

I've tried multiple solutions. Singleton, MemoryCache. But it will always slow down significantly.

\--

One thing to note is that I'm not sure that the RulesEngine itself is to blame because we don't have any CPU/memory statistics of the host (Azure Service Fabric), also we don't have any control because the ASF is from the SaaS provider.

So, probably best to close this issue. When I have more details, or found out what it was, I'll update this issue in the future.
