### ISSUE TITLE
Return string instead or bool

### ISSUE THREAD

**Issue by dambsst** [microsoft/RulesEngine#72]
Hello,
Having a rule engine based on Json is very great, but fmho it is limited by the fact that the results are limited to static values: **SuccessEvent** and **Actions**.
Would it be possible to dynamically assign the **SuccessEvent** string from inside **ReSettings** for example? And leave the interpretation to the developer then? We could return whatever we want, another Json for example.
Taking back the example with the "Discount to be applied to a customer", we could return different discount depending on the context or even the name of another function or rule to be called. It gives the developer lots of flexibility.
Thank you

**Comment by abbasc52** [comment]
Hi @dambsst ,
Could you provide some example on what needs to be dynamic?

As of now, **SuccessEvent** is a static string which can be returned when a rule succeeds.

**Actions**(in v3) on the other hand are dynamic, by default, we provide **OutputAction** which can return any object returned by an expression. It can even use any inputs passed to rulesEngine so you can configure it as you want.

Furthermore, you can also create and register your own custom actions to achieve any desired functionality. More details on  - https://github.com/microsoft/RulesEngine/wiki/Actions

From the description you mentioned, it very much aligns with **Actions**. Let me know if i am missing something.

**Comment by dambsst** [comment]
Hi @abbasc52 ,

I have seen the **Actions**(in v3) and yes I could use them to solve my scenario but first I would have to completely ignore the result of the **Expression** and only use my **custom Action**, and I loose the flexibility of **Expression** that can be stored externally (using **custom Action** I must recompile everything).

For example, consider the scenario where the **RuleEngine** is used to get the discount in percentage for a customer with a member card, and this discount is calculated using 3x criteria: 

- being student or senior: bonus +10%

- member since more 2x year

- discount bonus of 5% per year of membership until 20%

You can see that in this case, the first 2 rules and be executed easily using the existing **Expression**, but if I want to execute the 3rd rule I have to use the **custom Action** too. I can also ignore the Expression and use a **custom Action** only which does everything (in expression I return True always, and run my **custom Action** OnSuccess). 

But the main inconvenient now is that we loose the flexibility of **Expression**  (it can be stored externally in a database and modify easily). So if I want to update the third criteria with "6% per year" for example, then I must recompile the **custom Action** and rebuilt everything.

Best solution would be to be able to modify the **SuccessEvent** directly from the lambda expression, so I don't use the **custom Action** to keep the flexibility of lambda expression.

Thank you,

**Comment by abbasc52** [comment]
> Best solution would be to be able to modify the **SuccessEvent** directly from the lambda expression, so I don't use the **custom Action** to keep the flexibility of lambda expression.]


Hi @dambsst, Lets discuss further on this point.
When you say modify SuccessEvent directly from lambda expression, are you suggesting that:
- Expression in Rule should be able to return anything? (beyond `true` and `false`)
- The returned value should be made available via a field (preferably `successEvent`)

Let know if this is the expectation.

**Comment by abbasc52** [comment]
@dambsst i am closing this thread due to lack of activity. You can reopen it anytime if are still facing this issue
