### ISSUE TITLE
ActionResult class avaliable without using directive

### ISSUE THREAD

**Issue by tjaz-brelih** [microsoft/RulesEngine#81]
With version 3.0.0 classes **ActionResult** and **ActionRuleResult** are readily available in projects referencing RulesEngine NuGet package without the **using** directive.
These classes can be used throughout the project as if they were in the same namespace. This means there is no need to specify namespace name when referencing these classes.

The same also happens in every project that references projects containing RulesEngine NuGet package.
The main issue is with ActionResult classes from other namespaces, since "globally available" RulesEngine ActionResult is always used over other ActionResult classes (except when they are fully qualified).
There is no IntelliSense or compiler warning.
This becomes a breaking issue with ASP.NET Core controllers which can use ActionResult base classes as a return type.

**Comment by abbasc52** [comment]
Issue is fixed in v3.0.1
