### ISSUE TITLE
Outdated IRulesEngine interface - RulesEngine v2

### ISSUE THREAD

**Issue by David-Moreira** [microsoft/RulesEngine#90]
Hello @abbasc52 
I was about to use your engine, while maintaining the use of interface provided, but I noticed, the IRulesEngine seems to be outdated, the contract does not state everything that should make the **RulesEngine** implementation work integrally.
The **RulesEngine** is able to be instantiated with no workflows, but add new workflows with the AddWorkflow method. So at least the interface should reflect that.

**What Happened:**
Attempted to instantiate the RulesEngine implementation of the interface while using the "no workflows" constructor. Not able to add workflows.
![image](https://user-images.githubusercontent.com/22283161/103551454-438e4d80-4ea2-11eb-9967-7d79285c2641.png)

Currently, if you abide by the interface you'll end up having to construct a new RulesEngine object everytime you need to use different workflows.

**Proposed Solution:**
IRulesEngine should also contain:
- AddWorkflow
- ClearWorkflows
- RemoveWorkflow

**Current workaround:**
Well... using the concrete implementation... that has full functionality exposed. 😆

**Comment by abbasc52** [comment]
It was on the back of my mind, but clearly missed it. Do you need it in v2 or an update to latest version be enough?

**Comment by David-Moreira** [comment]
I haven't updated to latest yet, because I had customized the RE to emulate the Actions functionality you now provided, so I will soon now that they're available. So personally latest version is fine by me. Thank you.
Up to you, if you think that's worth a hotfix on v2. 👍

**Comment by David-Moreira** [comment]
**PS:** I just noticed that the latest version has this fixed.
I'll eventually update. Up to you if you want to hotfix v2. You can close the issue however you deem right.

**Comment by abbasc52** [comment]
@David-Moreira i will be closing this issue, since the solution is to upgrade RulesEngine to v3.
