### ISSUE TITLE
Evaluation of rules

### ISSUE THREAD

**Issue by ddltechy** [microsoft/RulesEngine#91]
Hi, I've downloaded this great library and been playing with it. While running the DemoApp, specifically the Discount rule example (basic),  I found that if you define the test case to match for the GiveDiscount30 rule, it always returns that the matched and applied rule is the GiveDiscount25.

If I set this info for my test case, I always get that the applied rule is GiveDiscount25:

            var basicInfo = "{\"name\": \"hello\",\"email\": \"abcy@xyz.com\",\"creditHistory\": \"good\",\"country\": \"canada\",\"loyalityFactor\": 4,\"totalPurchasesToDate\": 50000}";
            var orderInfo = "{\"totalOrders\": 6,\"recurringItems\": 2}";
            var telemetryInfo = "{\"noOfVisitsPerMonth\": 20,\"percentageOfBuyingToVisit\": 15}";

The GiveDiscount25 rule is set to (same as give in this repository):

"Expression": "input1.country != \"india\" AND input1.loyalityFactor >= **2** AND input1.totalPurchasesToDate >= **10000** AND input2.totalOrders > **2** AND input3.noOfVisitsPerMonth > **5**"

And the GiveDiscount30 rule is set to:

"Expression": "input1.loyalityFactor > **3** AND input1.totalPurchasesToDate >= **50000** AND input1.totalPurchasesToDate <= **100000** AND input2.totalOrders > **5** AND input3.noOfVisitsPerMonth > **15**"

The only way I get it to apply the GiveDiscount30 is if I set the country to "india" or if define it before the GiveDiscount25 in the Discount.json file.

Am I doing anything wrong or this is the right behavior?  

Thank you very much for your support!

**Comment by abbasc52** [comment]
Hi @ddltechy ,
The Rules are evaluated in order of which they are defined. If multiple rules succeed and you use onSuccess method, it will simply return the first Success output. 

You can still get info that GiveDiscount30 has succeeded or not by iterating through the rule result.

So to answer your question, if you want to prefer checking for GiveDiscount30 before GiveDiscount25. It should be placed before GiveDiscount25

**Comment by ddltechy** [comment]
Thanks @abbasc52 ! It's clear now.
