### ISSUE TITLE
Local params of rule are not getting refreshed

### ISSUE THREAD

**Issue by rahul24** [microsoft/RulesEngine#94]
Steps to repro:

1. Define workflow that has rules. Define local param in the rule.
2. Execute the workflow once.
3. Change the local param expression.
4. Remove / clear workflow 
5. Add workflow again
6. Execute the workflow again.

The rule engine is not using the new/modified local params part of the rule in the workflow.

**Comment by abbasc52** [comment]
Fixed in 3.0.2
